//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/system/input/functions/automine.java
//

#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Boolean.h"
#include "org/minima/system/Main.h"
#include "org/minima/system/brains/ConsensusHandler.h"
#include "org/minima/system/input/CommandFunction.h"
#include "org/minima/system/input/functions/automine.h"
#include "org/minima/utils/messages/Message.h"

@implementation OrgMinimaSystemInputFunctionsautomine

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgMinimaSystemInputFunctionsautomine_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)doFunctionWithNSStringArray:(IOSObjectArray *)zInput {
  NSString *onff = IOSObjectArray_Get(nil_chk(zInput), 1);
  jboolean mining = false;
  if ([((NSString *) nil_chk(IOSObjectArray_Get(zInput, 1))) isEqual:@"on"]) {
    mining = true;
  }
  OrgMinimaUtilsMessagesMessage *mine = [((OrgMinimaUtilsMessagesMessage *) nil_chk([self getResponseMessageWithNSString:OrgMinimaSystemBrainsConsensusHandler_CONSENSUS_ACTIVATEMINE])) addObjectWithNSString:@"automining" withId:JavaLangBoolean_valueOfWithBoolean_(mining)];
  [((OrgMinimaSystemBrainsConsensusHandler *) nil_chk([((OrgMinimaSystemMain *) nil_chk([self getMainHandler])) getConsensusHandler])) PostMessageWithOrgMinimaUtilsMessagesMessage:mine];
}

- (OrgMinimaSystemInputCommandFunction *)getNewFunction {
  return new_OrgMinimaSystemInputFunctionsautomine_init();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, 2, -1, -1, -1 },
    { NULL, "LOrgMinimaSystemInputCommandFunction;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(doFunctionWithNSStringArray:);
  methods[2].selector = @selector(getNewFunction);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "doFunction", "[LNSString;", "LJavaLangException;" };
  static const J2ObjcClassInfo _OrgMinimaSystemInputFunctionsautomine = { "automine", "org.minima.system.input.functions", ptrTable, methods, NULL, 7, 0x1, 3, 0, -1, -1, -1, -1, -1 };
  return &_OrgMinimaSystemInputFunctionsautomine;
}

@end

void OrgMinimaSystemInputFunctionsautomine_init(OrgMinimaSystemInputFunctionsautomine *self) {
  OrgMinimaSystemInputCommandFunction_initWithNSString_(self, @"automine");
  [self setHelpWithNSString:@"[on|off]" withNSString:@"Start mining with full CPU power. BootStrap measure." withNSString:@"Doesn't require you to send a transaction, just mines constantly."];
}

OrgMinimaSystemInputFunctionsautomine *new_OrgMinimaSystemInputFunctionsautomine_init() {
  J2OBJC_NEW_IMPL(OrgMinimaSystemInputFunctionsautomine, init)
}

OrgMinimaSystemInputFunctionsautomine *create_OrgMinimaSystemInputFunctionsautomine_init() {
  J2OBJC_CREATE_IMPL(OrgMinimaSystemInputFunctionsautomine, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgMinimaSystemInputFunctionsautomine)

J2OBJC_NAME_MAPPING(OrgMinimaSystemInputFunctionsautomine, "org.minima.system.input.functions", "OrgMinimaSystemInputFunctions")
