//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/system/input/functions/cleanscript.java
//

#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "org/minima/system/Main.h"
#include "org/minima/system/brains/ConsensusHandler.h"
#include "org/minima/system/brains/ConsensusUser.h"
#include "org/minima/system/input/CommandFunction.h"
#include "org/minima/system/input/functions/cleanscript.h"
#include "org/minima/utils/messages/Message.h"

@implementation OrgMinimaSystemInputFunctionscleanscript

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgMinimaSystemInputFunctionscleanscript_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)doFunctionWithNSStringArray:(IOSObjectArray *)zInput {
  NSString *script = IOSObjectArray_Get(nil_chk(zInput), 1);
  OrgMinimaUtilsMessagesMessage *rscript = [self getResponseMessageWithNSString:OrgMinimaSystemBrainsConsensusUser_CONSENSUS_CLEANSCRIPT];
  [((OrgMinimaUtilsMessagesMessage *) nil_chk(rscript)) addStringWithNSString:@"script" withNSString:script];
  [((OrgMinimaSystemBrainsConsensusHandler *) nil_chk([((OrgMinimaSystemMain *) nil_chk([self getMainHandler])) getConsensusHandler])) PostMessageWithOrgMinimaUtilsMessagesMessage:rscript];
}

- (OrgMinimaSystemInputCommandFunction *)getNewFunction {
  return create_OrgMinimaSystemInputFunctionscleanscript_init();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, 2, -1, -1, -1 },
    { NULL, "LOrgMinimaSystemInputCommandFunction;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(doFunctionWithNSStringArray:);
  methods[2].selector = @selector(getNewFunction);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "doFunction", "[LNSString;", "LJavaLangException;" };
  static const J2ObjcClassInfo _OrgMinimaSystemInputFunctionscleanscript = { "cleanscript", "org.minima.system.input.functions", ptrTable, methods, NULL, 7, 0x1, 3, 0, -1, -1, -1, -1, -1 };
  return &_OrgMinimaSystemInputFunctionscleanscript;
}

@end

void OrgMinimaSystemInputFunctionscleanscript_init(OrgMinimaSystemInputFunctionscleanscript *self) {
  OrgMinimaSystemInputCommandFunction_initWithNSString_(self, @"cleanscript");
  [self setHelpWithNSString:@"[script]" withNSString:@"Clean the script to make it a valid Minima script" withNSString:@""];
}

OrgMinimaSystemInputFunctionscleanscript *new_OrgMinimaSystemInputFunctionscleanscript_init() {
  J2OBJC_NEW_IMPL(OrgMinimaSystemInputFunctionscleanscript, init)
}

OrgMinimaSystemInputFunctionscleanscript *create_OrgMinimaSystemInputFunctionscleanscript_init() {
  J2OBJC_CREATE_IMPL(OrgMinimaSystemInputFunctionscleanscript, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgMinimaSystemInputFunctionscleanscript)

J2OBJC_NAME_MAPPING(OrgMinimaSystemInputFunctionscleanscript, "org.minima.system.input.functions", "OrgMinimaSystemInputFunctions")
