//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/system/input/functions/newscript.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaSystemInputFunctionsNewscript")
#ifdef RESTRICT_OrgMinimaSystemInputFunctionsNewscript
#define INCLUDE_ALL_OrgMinimaSystemInputFunctionsNewscript 0
#else
#define INCLUDE_ALL_OrgMinimaSystemInputFunctionsNewscript 1
#endif
#undef RESTRICT_OrgMinimaSystemInputFunctionsNewscript

#if !defined (OrgMinimaSystemInputFunctionsnewscript_) && (INCLUDE_ALL_OrgMinimaSystemInputFunctionsNewscript || defined(INCLUDE_OrgMinimaSystemInputFunctionsnewscript))
#define OrgMinimaSystemInputFunctionsnewscript_

#define RESTRICT_OrgMinimaSystemInputCommandFunction 1
#define INCLUDE_OrgMinimaSystemInputCommandFunction 1
#include "org/minima/system/input/CommandFunction.h"

@class IOSObjectArray;

@interface OrgMinimaSystemInputFunctionsnewscript : OrgMinimaSystemInputCommandFunction

#pragma mark Public

- (instancetype)init;

- (void)doFunctionWithNSStringArray:(IOSObjectArray *)zInput;

- (OrgMinimaSystemInputCommandFunction *)getNewFunction;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaSystemInputFunctionsnewscript)

FOUNDATION_EXPORT void OrgMinimaSystemInputFunctionsnewscript_init(OrgMinimaSystemInputFunctionsnewscript *self);

FOUNDATION_EXPORT OrgMinimaSystemInputFunctionsnewscript *new_OrgMinimaSystemInputFunctionsnewscript_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaSystemInputFunctionsnewscript *create_OrgMinimaSystemInputFunctionsnewscript_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaSystemInputFunctionsnewscript)

@compatibility_alias OrgMinimaSystemInputFunctionsNewscript OrgMinimaSystemInputFunctionsnewscript;

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaSystemInputFunctionsNewscript")
