//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/system/input/functions/printdb.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaSystemInputFunctionsPrintdb")
#ifdef RESTRICT_OrgMinimaSystemInputFunctionsPrintdb
#define INCLUDE_ALL_OrgMinimaSystemInputFunctionsPrintdb 0
#else
#define INCLUDE_ALL_OrgMinimaSystemInputFunctionsPrintdb 1
#endif
#undef RESTRICT_OrgMinimaSystemInputFunctionsPrintdb

#if !defined (OrgMinimaSystemInputFunctionsprintdb_) && (INCLUDE_ALL_OrgMinimaSystemInputFunctionsPrintdb || defined(INCLUDE_OrgMinimaSystemInputFunctionsprintdb))
#define OrgMinimaSystemInputFunctionsprintdb_

#define RESTRICT_OrgMinimaSystemInputCommandFunction 1
#define INCLUDE_OrgMinimaSystemInputCommandFunction 1
#include "org/minima/system/input/CommandFunction.h"

@class IOSObjectArray;

@interface OrgMinimaSystemInputFunctionsprintdb : OrgMinimaSystemInputCommandFunction

#pragma mark Public

- (instancetype)init;

- (void)doFunctionWithNSStringArray:(IOSObjectArray *)zInput;

- (OrgMinimaSystemInputCommandFunction *)getNewFunction;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaSystemInputFunctionsprintdb)

FOUNDATION_EXPORT void OrgMinimaSystemInputFunctionsprintdb_init(OrgMinimaSystemInputFunctionsprintdb *self);

FOUNDATION_EXPORT OrgMinimaSystemInputFunctionsprintdb *new_OrgMinimaSystemInputFunctionsprintdb_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaSystemInputFunctionsprintdb *create_OrgMinimaSystemInputFunctionsprintdb_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaSystemInputFunctionsprintdb)

@compatibility_alias OrgMinimaSystemInputFunctionsPrintdb OrgMinimaSystemInputFunctionsprintdb;

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaSystemInputFunctionsPrintdb")
