//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/system/input/functions/test.java
//

#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "org/minima/system/Main.h"
#include "org/minima/system/input/CommandFunction.h"
#include "org/minima/system/input/functions/test.h"
#include "org/minima/system/tx/TXMiner.h"

@implementation OrgMinimaSystemInputFunctionstest

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgMinimaSystemInputFunctionstest_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)doFunctionWithNSStringArray:(IOSObjectArray *)zInput {
  [((OrgMinimaSystemTxTXMiner *) nil_chk([((OrgMinimaSystemMain *) nil_chk([self getMainHandler])) getMiner])) PostMessageWithNSString:OrgMinimaSystemTxTXMiner_TXMINER_TESTHASHING];
}

- (OrgMinimaSystemInputCommandFunction *)getNewFunction {
  return create_OrgMinimaSystemInputFunctionstest_init();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, 2, -1, -1, -1 },
    { NULL, "LOrgMinimaSystemInputCommandFunction;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(doFunctionWithNSStringArray:);
  methods[2].selector = @selector(getNewFunction);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "doFunction", "[LNSString;", "LJavaLangException;" };
  static const J2ObjcClassInfo _OrgMinimaSystemInputFunctionstest = { "test", "org.minima.system.input.functions", ptrTable, methods, NULL, 7, 0x1, 3, 0, -1, -1, -1, -1, -1 };
  return &_OrgMinimaSystemInputFunctionstest;
}

@end

void OrgMinimaSystemInputFunctionstest_init(OrgMinimaSystemInputFunctionstest *self) {
  OrgMinimaSystemInputCommandFunction_initWithNSString_(self, @"test");
  [self setHelpWithNSString:@"" withNSString:@"Test the hashrate of the machine you are using.." withNSString:@"Test the hashrate of the machine you are using.."];
}

OrgMinimaSystemInputFunctionstest *new_OrgMinimaSystemInputFunctionstest_init() {
  J2OBJC_NEW_IMPL(OrgMinimaSystemInputFunctionstest, init)
}

OrgMinimaSystemInputFunctionstest *create_OrgMinimaSystemInputFunctionstest_init() {
  J2OBJC_CREATE_IMPL(OrgMinimaSystemInputFunctionstest, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgMinimaSystemInputFunctionstest)

J2OBJC_NAME_MAPPING(OrgMinimaSystemInputFunctionstest, "org.minima.system.input.functions", "OrgMinimaSystemInputFunctions")
