//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/system/bootstrap/GenesisTxPOW.java
//

#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "java/io/ByteArrayInputStream.h"
#include "java/io/ByteArrayOutputStream.h"
#include "java/io/DataInputStream.h"
#include "java/io/DataOutputStream.h"
#include "java/io/PrintStream.h"
#include "java/lang/Exception.h"
#include "java/lang/System.h"
#include "org/minima/objects/Transaction.h"
#include "org/minima/objects/TxPOW.h"
#include "org/minima/objects/Witness.h"
#include "org/minima/objects/base/MiniData.h"
#include "org/minima/objects/base/MiniData32.h"
#include "org/minima/objects/base/MiniNumber.h"
#include "org/minima/system/bootstrap/GenesisTxPOW.h"

J2OBJC_INITIALIZED_DEFN(OrgMinimaSystemBootstrapGenesisTxPOW)

OrgMinimaObjectsBaseMiniData32 *OrgMinimaSystemBootstrapGenesisTxPOW_GENESIS_INPUT;

@implementation OrgMinimaSystemBootstrapGenesisTxPOW

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgMinimaSystemBootstrapGenesisTxPOW_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (void)mainWithNSStringArray:(IOSObjectArray *)zArgs {
  OrgMinimaSystemBootstrapGenesisTxPOW_mainWithNSStringArray_(zArgs);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(mainWithNSStringArray:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "GENESIS_INPUT", "LOrgMinimaObjectsBaseMiniData32;", .constantValue.asLong = 0, 0x9, -1, 2, -1, -1 },
  };
  static const void *ptrTable[] = { "main", "[LNSString;", &OrgMinimaSystemBootstrapGenesisTxPOW_GENESIS_INPUT };
  static const J2ObjcClassInfo _OrgMinimaSystemBootstrapGenesisTxPOW = { "GenesisTxPOW", "org.minima.system.bootstrap", ptrTable, methods, fields, 7, 0x1, 2, 1, -1, -1, -1, -1, -1 };
  return &_OrgMinimaSystemBootstrapGenesisTxPOW;
}

+ (void)initialize {
  if (self == [OrgMinimaSystemBootstrapGenesisTxPOW class]) {
    JreStrongAssignAndConsume(&OrgMinimaSystemBootstrapGenesisTxPOW_GENESIS_INPUT, new_OrgMinimaObjectsBaseMiniData32_initWithNSString_(@"0xFFEEDDCCBBAA998877665544332211"));
    J2OBJC_SET_INITIALIZED(OrgMinimaSystemBootstrapGenesisTxPOW)
  }
}

@end

void OrgMinimaSystemBootstrapGenesisTxPOW_init(OrgMinimaSystemBootstrapGenesisTxPOW *self) {
  OrgMinimaObjectsTxPOW_init(self);
  [self setTxDifficultyWithInt:0];
  [self setNonceWithOrgMinimaObjectsBaseMiniNumber:create_OrgMinimaObjectsBaseMiniNumber_initWithNSString_(@"256")];
  [self setTimeMilliWithOrgMinimaObjectsBaseMiniNumber:create_OrgMinimaObjectsBaseMiniNumber_initWithNSString_(JreStrcat("J", JavaLangSystem_currentTimeMillis()))];
  [self setBlockNumberWithOrgMinimaObjectsBaseMiniNumber:create_OrgMinimaObjectsBaseMiniNumber_initWithNSString_(@"0")];
  [self setBlockDifficultyWithInt:0];
  [self setParentWithOrgMinimaObjectsBaseMiniData32:create_OrgMinimaObjectsBaseMiniData32_init()];
  OrgMinimaObjectsTransaction *trans = create_OrgMinimaObjectsTransaction_init();
  OrgMinimaObjectsWitness *wit = create_OrgMinimaObjectsWitness_init();
  [self setTransactionWithOrgMinimaObjectsTransaction:trans];
  [self setWitnessWithOrgMinimaObjectsWitness:wit];
  IOSObjectArray_SetAndConsume(nil_chk(self->mSuperParents_), 0, new_OrgMinimaObjectsBaseMiniData32_initWithByteArray_([((OrgMinimaObjectsBaseMiniData *) nil_chk(OrgMinimaObjectsBaseMiniData_getRandomDataWithInt_(32))) getData]));
  [self calculateTXPOWID];
  self->_mIsBlockPOW_ = true;
  self->_mIsTxnPOW_ = false;
}

OrgMinimaSystemBootstrapGenesisTxPOW *new_OrgMinimaSystemBootstrapGenesisTxPOW_init() {
  J2OBJC_NEW_IMPL(OrgMinimaSystemBootstrapGenesisTxPOW, init)
}

OrgMinimaSystemBootstrapGenesisTxPOW *create_OrgMinimaSystemBootstrapGenesisTxPOW_init() {
  J2OBJC_CREATE_IMPL(OrgMinimaSystemBootstrapGenesisTxPOW, init)
}

void OrgMinimaSystemBootstrapGenesisTxPOW_mainWithNSStringArray_(IOSObjectArray *zArgs) {
  OrgMinimaSystemBootstrapGenesisTxPOW_initialize();
  OrgMinimaSystemBootstrapGenesisTxPOW *gen = create_OrgMinimaSystemBootstrapGenesisTxPOW_init();
  @try {
    [((JavaIoPrintStream *) nil_chk(JreLoadStatic(JavaLangSystem, out))) printlnWithNSString:JreStrcat("$@", @"GEN 1 : ", gen)];
    JavaIoByteArrayOutputStream *baos = create_JavaIoByteArrayOutputStream_init();
    JavaIoDataOutputStream *dos = create_JavaIoDataOutputStream_initWithJavaIoOutputStream_(baos);
    [gen writeDataStreamWithJavaIoDataOutputStream:dos];
    [dos flush];
    IOSByteArray *data = [baos toByteArray];
    JavaIoByteArrayInputStream *bais = create_JavaIoByteArrayInputStream_initWithByteArray_(data);
    JavaIoDataInputStream *dis = create_JavaIoDataInputStream_initWithJavaIoInputStream_(bais);
    OrgMinimaObjectsTxPOW *tp = create_OrgMinimaObjectsTxPOW_init();
    [tp readDataStreamWithJavaIoDataInputStream:dis];
    [((JavaIoPrintStream *) nil_chk(JreLoadStatic(JavaLangSystem, out))) printlnWithNSString:JreStrcat("$@", @"GEN 2 : ", tp)];
  }
  @catch (JavaLangException *exc) {
    [exc printStackTrace];
  }
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgMinimaSystemBootstrapGenesisTxPOW)
