//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/system/bootstrap/GenesisTransaction.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaSystemBootstrapGenesisTransaction")
#ifdef RESTRICT_OrgMinimaSystemBootstrapGenesisTransaction
#define INCLUDE_ALL_OrgMinimaSystemBootstrapGenesisTransaction 0
#else
#define INCLUDE_ALL_OrgMinimaSystemBootstrapGenesisTransaction 1
#endif
#undef RESTRICT_OrgMinimaSystemBootstrapGenesisTransaction

#if !defined (OrgMinimaSystemBootstrapGenesisTransaction_) && (INCLUDE_ALL_OrgMinimaSystemBootstrapGenesisTransaction || defined(INCLUDE_OrgMinimaSystemBootstrapGenesisTransaction))
#define OrgMinimaSystemBootstrapGenesisTransaction_

#define RESTRICT_OrgMinimaObjectsTransaction 1
#define INCLUDE_OrgMinimaObjectsTransaction 1
#include "org/minima/objects/Transaction.h"

@interface OrgMinimaSystemBootstrapGenesisTransaction : OrgMinimaObjectsTransaction

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaSystemBootstrapGenesisTransaction)

FOUNDATION_EXPORT void OrgMinimaSystemBootstrapGenesisTransaction_init(OrgMinimaSystemBootstrapGenesisTransaction *self);

FOUNDATION_EXPORT OrgMinimaSystemBootstrapGenesisTransaction *new_OrgMinimaSystemBootstrapGenesisTransaction_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaSystemBootstrapGenesisTransaction *create_OrgMinimaSystemBootstrapGenesisTransaction_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaSystemBootstrapGenesisTransaction)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaSystemBootstrapGenesisTransaction")
