//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/kissvm/functions/base/HEXCAT.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaKissvmFunctionsBaseHEXCAT")
#ifdef RESTRICT_OrgMinimaKissvmFunctionsBaseHEXCAT
#define INCLUDE_ALL_OrgMinimaKissvmFunctionsBaseHEXCAT 0
#else
#define INCLUDE_ALL_OrgMinimaKissvmFunctionsBaseHEXCAT 1
#endif
#undef RESTRICT_OrgMinimaKissvmFunctionsBaseHEXCAT

#if !defined (OrgMinimaKissvmFunctionsBaseHEXCAT_) && (INCLUDE_ALL_OrgMinimaKissvmFunctionsBaseHEXCAT || defined(INCLUDE_OrgMinimaKissvmFunctionsBaseHEXCAT))
#define OrgMinimaKissvmFunctionsBaseHEXCAT_

#define RESTRICT_OrgMinimaKissvmFunctionsMinimaFunction 1
#define INCLUDE_OrgMinimaKissvmFunctionsMinimaFunction 1
#include "org/minima/kissvm/functions/MinimaFunction.h"

@class OrgMinimaKissvmContract;
@class OrgMinimaKissvmValuesValue;

@interface OrgMinimaKissvmFunctionsBaseHEXCAT : OrgMinimaKissvmFunctionsMinimaFunction

#pragma mark Public

- (instancetype)init;

- (OrgMinimaKissvmFunctionsMinimaFunction *)getNewFunction;

- (OrgMinimaKissvmValuesValue *)runFunctionWithOrgMinimaKissvmContract:(OrgMinimaKissvmContract *)zContract;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaKissvmFunctionsBaseHEXCAT)

FOUNDATION_EXPORT void OrgMinimaKissvmFunctionsBaseHEXCAT_init(OrgMinimaKissvmFunctionsBaseHEXCAT *self);

FOUNDATION_EXPORT OrgMinimaKissvmFunctionsBaseHEXCAT *new_OrgMinimaKissvmFunctionsBaseHEXCAT_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaKissvmFunctionsBaseHEXCAT *create_OrgMinimaKissvmFunctionsBaseHEXCAT_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaKissvmFunctionsBaseHEXCAT)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaKissvmFunctionsBaseHEXCAT")
