//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/kissvm/functions/base/REV.java
//

#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "org/minima/kissvm/Contract.h"
#include "org/minima/kissvm/expressions/Expression.h"
#include "org/minima/kissvm/functions/MinimaFunction.h"
#include "org/minima/kissvm/functions/base/REV.h"
#include "org/minima/kissvm/values/HEXValue.h"
#include "org/minima/kissvm/values/Value.h"

@implementation OrgMinimaKissvmFunctionsBaseREV

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgMinimaKissvmFunctionsBaseREV_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (OrgMinimaKissvmValuesValue *)runFunctionWithOrgMinimaKissvmContract:(OrgMinimaKissvmContract *)zContract {
  IOSByteArray *array = [((OrgMinimaKissvmValuesValue *) nil_chk([((id<OrgMinimaKissvmExpressionsExpression>) nil_chk([self getParameterWithInt:0])) getValueWithOrgMinimaKissvmContract:zContract])) getRawData];
  jint datalen = ((IOSByteArray *) nil_chk(array))->size_;
  IOSByteArray *revdata = [IOSByteArray arrayWithLength:datalen];
  for (jint i = 0; i < datalen; i++) {
    *IOSByteArray_GetRef(revdata, i) = IOSByteArray_Get(array, array->size_ - i - 1);
  }
  return create_OrgMinimaKissvmValuesHEXValue_initWithByteArray_(revdata);
}

- (OrgMinimaKissvmFunctionsMinimaFunction *)getNewFunction {
  return create_OrgMinimaKissvmFunctionsBaseREV_init();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgMinimaKissvmValuesValue;", 0x1, 0, 1, 2, -1, -1, -1 },
    { NULL, "LOrgMinimaKissvmFunctionsMinimaFunction;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(runFunctionWithOrgMinimaKissvmContract:);
  methods[2].selector = @selector(getNewFunction);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "runFunction", "LOrgMinimaKissvmContract;", "LOrgMinimaKissvmExceptionsExecutionException;" };
  static const J2ObjcClassInfo _OrgMinimaKissvmFunctionsBaseREV = { "REV", "org.minima.kissvm.functions.base", ptrTable, methods, NULL, 7, 0x1, 3, 0, -1, -1, -1, -1, -1 };
  return &_OrgMinimaKissvmFunctionsBaseREV;
}

@end

void OrgMinimaKissvmFunctionsBaseREV_init(OrgMinimaKissvmFunctionsBaseREV *self) {
  OrgMinimaKissvmFunctionsMinimaFunction_initWithNSString_(self, @"REV");
}

OrgMinimaKissvmFunctionsBaseREV *new_OrgMinimaKissvmFunctionsBaseREV_init() {
  J2OBJC_NEW_IMPL(OrgMinimaKissvmFunctionsBaseREV, init)
}

OrgMinimaKissvmFunctionsBaseREV *create_OrgMinimaKissvmFunctionsBaseREV_init() {
  J2OBJC_CREATE_IMPL(OrgMinimaKissvmFunctionsBaseREV, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgMinimaKissvmFunctionsBaseREV)
