//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/utils/messages/MessageStack.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaUtilsMessagesMessageStack")
#ifdef RESTRICT_OrgMinimaUtilsMessagesMessageStack
#define INCLUDE_ALL_OrgMinimaUtilsMessagesMessageStack 0
#else
#define INCLUDE_ALL_OrgMinimaUtilsMessagesMessageStack 1
#endif
#undef RESTRICT_OrgMinimaUtilsMessagesMessageStack

#if !defined (OrgMinimaUtilsMessagesMessageStack_) && (INCLUDE_ALL_OrgMinimaUtilsMessagesMessageStack || defined(INCLUDE_OrgMinimaUtilsMessagesMessageStack))
#define OrgMinimaUtilsMessagesMessageStack_

@class OrgMinimaUtilsMessagesMessage;

@interface OrgMinimaUtilsMessagesMessageStack : NSObject

#pragma mark Public

- (instancetype)init;

- (void)PostMessageWithOrgMinimaUtilsMessagesMessage:(OrgMinimaUtilsMessagesMessage *)zMessage;

- (void)PostMessageWithNSString:(NSString *)zMessage;

#pragma mark Protected

- (OrgMinimaUtilsMessagesMessage *)getNextMessage;

- (jint)getSize;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaUtilsMessagesMessageStack)

FOUNDATION_EXPORT void OrgMinimaUtilsMessagesMessageStack_init(OrgMinimaUtilsMessagesMessageStack *self);

FOUNDATION_EXPORT OrgMinimaUtilsMessagesMessageStack *new_OrgMinimaUtilsMessagesMessageStack_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaUtilsMessagesMessageStack *create_OrgMinimaUtilsMessagesMessageStack_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaUtilsMessagesMessageStack)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaUtilsMessagesMessageStack")
