//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/database/coindb/sql/SQLCoinDB.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaDatabaseCoindbSqlSQLCoinDB")
#ifdef RESTRICT_OrgMinimaDatabaseCoindbSqlSQLCoinDB
#define INCLUDE_ALL_OrgMinimaDatabaseCoindbSqlSQLCoinDB 0
#else
#define INCLUDE_ALL_OrgMinimaDatabaseCoindbSqlSQLCoinDB 1
#endif
#undef RESTRICT_OrgMinimaDatabaseCoindbSqlSQLCoinDB

#if !defined (OrgMinimaDatabaseCoindbSqlSQLCoinDB_) && (INCLUDE_ALL_OrgMinimaDatabaseCoindbSqlSQLCoinDB || defined(INCLUDE_OrgMinimaDatabaseCoindbSqlSQLCoinDB))
#define OrgMinimaDatabaseCoindbSqlSQLCoinDB_

@interface OrgMinimaDatabaseCoindbSqlSQLCoinDB : NSObject

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaDatabaseCoindbSqlSQLCoinDB)

FOUNDATION_EXPORT void OrgMinimaDatabaseCoindbSqlSQLCoinDB_init(OrgMinimaDatabaseCoindbSqlSQLCoinDB *self);

FOUNDATION_EXPORT OrgMinimaDatabaseCoindbSqlSQLCoinDB *new_OrgMinimaDatabaseCoindbSqlSQLCoinDB_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaDatabaseCoindbSqlSQLCoinDB *create_OrgMinimaDatabaseCoindbSqlSQLCoinDB_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaDatabaseCoindbSqlSQLCoinDB)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaDatabaseCoindbSqlSQLCoinDB")
