//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/utils/BaseConverter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaUtilsBaseConverter")
#ifdef RESTRICT_OrgMinimaUtilsBaseConverter
#define INCLUDE_ALL_OrgMinimaUtilsBaseConverter 0
#else
#define INCLUDE_ALL_OrgMinimaUtilsBaseConverter 1
#endif
#undef RESTRICT_OrgMinimaUtilsBaseConverter

#if !defined (OrgMinimaUtilsBaseConverter_) && (INCLUDE_ALL_OrgMinimaUtilsBaseConverter || defined(INCLUDE_OrgMinimaUtilsBaseConverter))
#define OrgMinimaUtilsBaseConverter_

@class IOSByteArray;
@class IOSObjectArray;

@interface OrgMinimaUtilsBaseConverter : NSObject

#pragma mark Public

- (instancetype)init;

+ (IOSByteArray *)decode16WithNSString:(NSString *)zHex;

+ (IOSByteArray *)decode32WithNSString:(NSString *)zHex32;

+ (NSString *)encode16WithByteArray:(IOSByteArray *)bytes;

+ (NSString *)encode32WithByteArray:(IOSByteArray *)zData;

+ (void)mainWithNSStringArray:(IOSObjectArray *)zArgs;

@end

J2OBJC_STATIC_INIT(OrgMinimaUtilsBaseConverter)

FOUNDATION_EXPORT void OrgMinimaUtilsBaseConverter_init(OrgMinimaUtilsBaseConverter *self);

FOUNDATION_EXPORT OrgMinimaUtilsBaseConverter *new_OrgMinimaUtilsBaseConverter_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaUtilsBaseConverter *create_OrgMinimaUtilsBaseConverter_init(void);

FOUNDATION_EXPORT NSString *OrgMinimaUtilsBaseConverter_encode16WithByteArray_(IOSByteArray *bytes);

FOUNDATION_EXPORT IOSByteArray *OrgMinimaUtilsBaseConverter_decode16WithNSString_(NSString *zHex);

FOUNDATION_EXPORT NSString *OrgMinimaUtilsBaseConverter_encode32WithByteArray_(IOSByteArray *zData);

FOUNDATION_EXPORT IOSByteArray *OrgMinimaUtilsBaseConverter_decode32WithNSString_(NSString *zHex32);

FOUNDATION_EXPORT void OrgMinimaUtilsBaseConverter_mainWithNSStringArray_(IOSObjectArray *zArgs);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaUtilsBaseConverter)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaUtilsBaseConverter")
