//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/utils/Maths.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaUtilsMaths")
#ifdef RESTRICT_OrgMinimaUtilsMaths
#define INCLUDE_ALL_OrgMinimaUtilsMaths 0
#else
#define INCLUDE_ALL_OrgMinimaUtilsMaths 1
#endif
#undef RESTRICT_OrgMinimaUtilsMaths

#if !defined (OrgMinimaUtilsMaths_) && (INCLUDE_ALL_OrgMinimaUtilsMaths || defined(INCLUDE_OrgMinimaUtilsMaths))
#define OrgMinimaUtilsMaths_

@class IOSByteArray;
@class JavaMathBigDecimal;
@class JavaMathBigInteger;

@interface OrgMinimaUtilsMaths : NSObject

#pragma mark Public

- (instancetype)init;

+ (NSString *)ConvertMilliToTimeWithLong:(jlong)zMilli;

+ (NSString *)getDataAsStringWithByteArray:(IOSByteArray *)zData;

+ (jdouble)log2WithDouble:(jdouble)zDD;

+ (jdouble)log2BIWithJavaMathBigInteger:(JavaMathBigInteger *)val;

@end

J2OBJC_STATIC_INIT(OrgMinimaUtilsMaths)

inline JavaMathBigInteger *OrgMinimaUtilsMaths_get_BI_TWO(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT JavaMathBigInteger *OrgMinimaUtilsMaths_BI_TWO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgMinimaUtilsMaths, BI_TWO, JavaMathBigInteger *)

inline JavaMathBigDecimal *OrgMinimaUtilsMaths_get_BD_TWO(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT JavaMathBigDecimal *OrgMinimaUtilsMaths_BD_TWO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgMinimaUtilsMaths, BD_TWO, JavaMathBigDecimal *)

FOUNDATION_EXPORT void OrgMinimaUtilsMaths_init(OrgMinimaUtilsMaths *self);

FOUNDATION_EXPORT OrgMinimaUtilsMaths *new_OrgMinimaUtilsMaths_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaUtilsMaths *create_OrgMinimaUtilsMaths_init(void);

FOUNDATION_EXPORT jdouble OrgMinimaUtilsMaths_log2WithDouble_(jdouble zDD);

FOUNDATION_EXPORT NSString *OrgMinimaUtilsMaths_getDataAsStringWithByteArray_(IOSByteArray *zData);

FOUNDATION_EXPORT jdouble OrgMinimaUtilsMaths_log2BIWithJavaMathBigInteger_(JavaMathBigInteger *val);

FOUNDATION_EXPORT NSString *OrgMinimaUtilsMaths_ConvertMilliToTimeWithLong_(jlong zMilli);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaUtilsMaths)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaUtilsMaths")
