//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/utils/PostReqEx.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaUtilsPostReqEx")
#ifdef RESTRICT_OrgMinimaUtilsPostReqEx
#define INCLUDE_ALL_OrgMinimaUtilsPostReqEx 0
#else
#define INCLUDE_ALL_OrgMinimaUtilsPostReqEx 1
#endif
#undef RESTRICT_OrgMinimaUtilsPostReqEx

#if !defined (OrgMinimaUtilsPostReqEx_) && (INCLUDE_ALL_OrgMinimaUtilsPostReqEx || defined(INCLUDE_OrgMinimaUtilsPostReqEx))
#define OrgMinimaUtilsPostReqEx_

@class IOSObjectArray;

@interface OrgMinimaUtilsPostReqEx : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)mainWithNSStringArray:(IOSObjectArray *)zArgs;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaUtilsPostReqEx)

FOUNDATION_EXPORT void OrgMinimaUtilsPostReqEx_init(OrgMinimaUtilsPostReqEx *self);

FOUNDATION_EXPORT OrgMinimaUtilsPostReqEx *new_OrgMinimaUtilsPostReqEx_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaUtilsPostReqEx *create_OrgMinimaUtilsPostReqEx_init(void);

FOUNDATION_EXPORT void OrgMinimaUtilsPostReqEx_mainWithNSStringArray_(IOSObjectArray *zArgs);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaUtilsPostReqEx)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaUtilsPostReqEx")
