//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/utils/Streamable.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaUtilsStreamable")
#ifdef RESTRICT_OrgMinimaUtilsStreamable
#define INCLUDE_ALL_OrgMinimaUtilsStreamable 0
#else
#define INCLUDE_ALL_OrgMinimaUtilsStreamable 1
#endif
#undef RESTRICT_OrgMinimaUtilsStreamable

#if !defined (OrgMinimaUtilsStreamable_) && (INCLUDE_ALL_OrgMinimaUtilsStreamable || defined(INCLUDE_OrgMinimaUtilsStreamable))
#define OrgMinimaUtilsStreamable_

@class JavaIoDataInputStream;
@class JavaIoDataOutputStream;

@protocol OrgMinimaUtilsStreamable < JavaObject >

- (void)writeDataStreamWithJavaIoDataOutputStream:(JavaIoDataOutputStream *)zOut;

- (void)readDataStreamWithJavaIoDataInputStream:(JavaIoDataInputStream *)zIn;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaUtilsStreamable)

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaUtilsStreamable)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaUtilsStreamable")
