//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/system/network/rpc/RPCClient.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaSystemNetworkRpcRPCClient")
#ifdef RESTRICT_OrgMinimaSystemNetworkRpcRPCClient
#define INCLUDE_ALL_OrgMinimaSystemNetworkRpcRPCClient 0
#else
#define INCLUDE_ALL_OrgMinimaSystemNetworkRpcRPCClient 1
#endif
#undef RESTRICT_OrgMinimaSystemNetworkRpcRPCClient

#if !defined (OrgMinimaSystemNetworkRpcRPCClient_) && (INCLUDE_ALL_OrgMinimaSystemNetworkRpcRPCClient || defined(INCLUDE_OrgMinimaSystemNetworkRpcRPCClient))
#define OrgMinimaSystemNetworkRpcRPCClient_

@class IOSObjectArray;

@interface OrgMinimaSystemNetworkRpcRPCClient : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)mainWithNSStringArray:(IOSObjectArray *)zArgs;

+ (NSString *)sendGETWithNSString:(NSString *)zHost;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaSystemNetworkRpcRPCClient)

inline NSString *OrgMinimaSystemNetworkRpcRPCClient_get_USER_AGENT(void);
inline NSString *OrgMinimaSystemNetworkRpcRPCClient_set_USER_AGENT(NSString *value);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgMinimaSystemNetworkRpcRPCClient_USER_AGENT;
J2OBJC_STATIC_FIELD_OBJ(OrgMinimaSystemNetworkRpcRPCClient, USER_AGENT, NSString *)

FOUNDATION_EXPORT void OrgMinimaSystemNetworkRpcRPCClient_init(OrgMinimaSystemNetworkRpcRPCClient *self);

FOUNDATION_EXPORT OrgMinimaSystemNetworkRpcRPCClient *new_OrgMinimaSystemNetworkRpcRPCClient_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaSystemNetworkRpcRPCClient *create_OrgMinimaSystemNetworkRpcRPCClient_init(void);

FOUNDATION_EXPORT NSString *OrgMinimaSystemNetworkRpcRPCClient_sendGETWithNSString_(NSString *zHost);

FOUNDATION_EXPORT void OrgMinimaSystemNetworkRpcRPCClient_mainWithNSStringArray_(IOSObjectArray *zArgs);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaSystemNetworkRpcRPCClient)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaSystemNetworkRpcRPCClient")
