//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/system/network/rpc/RPCHandler.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaSystemNetworkRpcRPCHandler")
#ifdef RESTRICT_OrgMinimaSystemNetworkRpcRPCHandler
#define INCLUDE_ALL_OrgMinimaSystemNetworkRpcRPCHandler 0
#else
#define INCLUDE_ALL_OrgMinimaSystemNetworkRpcRPCHandler 1
#endif
#undef RESTRICT_OrgMinimaSystemNetworkRpcRPCHandler

#if !defined (OrgMinimaSystemNetworkRpcRPCHandler_) && (INCLUDE_ALL_OrgMinimaSystemNetworkRpcRPCHandler || defined(INCLUDE_OrgMinimaSystemNetworkRpcRPCHandler))
#define OrgMinimaSystemNetworkRpcRPCHandler_

#define RESTRICT_JavaLangRunnable 1
#define INCLUDE_JavaLangRunnable 1
#include "java/lang/Runnable.h"

@class JavaNetSocket;
@class OrgMinimaSystemInputInputHandler;

@interface OrgMinimaSystemNetworkRpcRPCHandler : NSObject < JavaLangRunnable > {
 @public
  JavaNetSocket *mSocket_;
  OrgMinimaSystemInputInputHandler *mInputHandler_;
}

#pragma mark Public

- (instancetype)initWithJavaNetSocket:(JavaNetSocket *)zSocket
 withOrgMinimaSystemInputInputHandler:(OrgMinimaSystemInputInputHandler *)zInput;

- (void)run;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaSystemNetworkRpcRPCHandler)

J2OBJC_FIELD_SETTER(OrgMinimaSystemNetworkRpcRPCHandler, mSocket_, JavaNetSocket *)
J2OBJC_FIELD_SETTER(OrgMinimaSystemNetworkRpcRPCHandler, mInputHandler_, OrgMinimaSystemInputInputHandler *)

FOUNDATION_EXPORT void OrgMinimaSystemNetworkRpcRPCHandler_initWithJavaNetSocket_withOrgMinimaSystemInputInputHandler_(OrgMinimaSystemNetworkRpcRPCHandler *self, JavaNetSocket *zSocket, OrgMinimaSystemInputInputHandler *zInput);

FOUNDATION_EXPORT OrgMinimaSystemNetworkRpcRPCHandler *new_OrgMinimaSystemNetworkRpcRPCHandler_initWithJavaNetSocket_withOrgMinimaSystemInputInputHandler_(JavaNetSocket *zSocket, OrgMinimaSystemInputInputHandler *zInput) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaSystemNetworkRpcRPCHandler *create_OrgMinimaSystemNetworkRpcRPCHandler_initWithJavaNetSocket_withOrgMinimaSystemInputInputHandler_(JavaNetSocket *zSocket, OrgMinimaSystemInputInputHandler *zInput);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaSystemNetworkRpcRPCHandler)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaSystemNetworkRpcRPCHandler")
