//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/system/network/rpc/RPCServer.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaSystemNetworkRpcRPCServer")
#ifdef RESTRICT_OrgMinimaSystemNetworkRpcRPCServer
#define INCLUDE_ALL_OrgMinimaSystemNetworkRpcRPCServer 0
#else
#define INCLUDE_ALL_OrgMinimaSystemNetworkRpcRPCServer 1
#endif
#undef RESTRICT_OrgMinimaSystemNetworkRpcRPCServer

#if !defined (OrgMinimaSystemNetworkRpcRPCServer_) && (INCLUDE_ALL_OrgMinimaSystemNetworkRpcRPCServer || defined(INCLUDE_OrgMinimaSystemNetworkRpcRPCServer))
#define OrgMinimaSystemNetworkRpcRPCServer_

#define RESTRICT_JavaLangRunnable 1
#define INCLUDE_JavaLangRunnable 1
#include "java/lang/Runnable.h"

@class JavaNetServerSocket;
@class OrgMinimaSystemInputInputHandler;

@interface OrgMinimaSystemNetworkRpcRPCServer : NSObject < JavaLangRunnable > {
 @public
  OrgMinimaSystemInputInputHandler *mInputHandler_;
  JavaNetServerSocket *mServerSocket_;
  jint mPort_;
  jboolean mRunning_;
}

#pragma mark Public

- (instancetype)initWithOrgMinimaSystemInputInputHandler:(OrgMinimaSystemInputInputHandler *)zInput
                                                 withInt:(jint)zPort;

+ (NSString *)getHost;

- (jint)getPort;

- (void)run;

- (void)stop;

#pragma mark Package-Private

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaSystemNetworkRpcRPCServer)

J2OBJC_FIELD_SETTER(OrgMinimaSystemNetworkRpcRPCServer, mInputHandler_, OrgMinimaSystemInputInputHandler *)
J2OBJC_FIELD_SETTER(OrgMinimaSystemNetworkRpcRPCServer, mServerSocket_, JavaNetServerSocket *)

inline NSString *OrgMinimaSystemNetworkRpcRPCServer_get_mHost(void);
inline NSString *OrgMinimaSystemNetworkRpcRPCServer_set_mHost(NSString *value);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgMinimaSystemNetworkRpcRPCServer_mHost;
J2OBJC_STATIC_FIELD_OBJ(OrgMinimaSystemNetworkRpcRPCServer, mHost, NSString *)

FOUNDATION_EXPORT void OrgMinimaSystemNetworkRpcRPCServer_initWithOrgMinimaSystemInputInputHandler_withInt_(OrgMinimaSystemNetworkRpcRPCServer *self, OrgMinimaSystemInputInputHandler *zInput, jint zPort);

FOUNDATION_EXPORT OrgMinimaSystemNetworkRpcRPCServer *new_OrgMinimaSystemNetworkRpcRPCServer_initWithOrgMinimaSystemInputInputHandler_withInt_(OrgMinimaSystemInputInputHandler *zInput, jint zPort) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaSystemNetworkRpcRPCServer *create_OrgMinimaSystemNetworkRpcRPCServer_initWithOrgMinimaSystemInputInputHandler_withInt_(OrgMinimaSystemInputInputHandler *zInput, jint zPort);

FOUNDATION_EXPORT NSString *OrgMinimaSystemNetworkRpcRPCServer_getHost(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaSystemNetworkRpcRPCServer)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaSystemNetworkRpcRPCServer")
