//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/database/mmr/MMRSet.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaDatabaseMmrMMRSet")
#ifdef RESTRICT_OrgMinimaDatabaseMmrMMRSet
#define INCLUDE_ALL_OrgMinimaDatabaseMmrMMRSet 0
#else
#define INCLUDE_ALL_OrgMinimaDatabaseMmrMMRSet 1
#endif
#undef RESTRICT_OrgMinimaDatabaseMmrMMRSet

#if !defined (OrgMinimaDatabaseMmrMMRSet_) && (INCLUDE_ALL_OrgMinimaDatabaseMmrMMRSet || defined(INCLUDE_OrgMinimaDatabaseMmrMMRSet))
#define OrgMinimaDatabaseMmrMMRSet_

#define RESTRICT_OrgMinimaUtilsStreamable 1
#define INCLUDE_OrgMinimaUtilsStreamable 1
#include "org/minima/utils/Streamable.h"

@class IOSObjectArray;
@class JavaIoDataInputStream;
@class JavaIoDataOutputStream;
@class JavaUtilArrayList;
@class OrgMinimaDatabaseMmrMMRData;
@class OrgMinimaDatabaseMmrMMREntry;
@class OrgMinimaDatabaseMmrMMRProof;
@class OrgMinimaObjectsBaseMiniData;
@class OrgMinimaObjectsBaseMiniInteger;
@class OrgMinimaObjectsBaseMiniNumber;

@interface OrgMinimaDatabaseMmrMMRSet : NSObject < OrgMinimaUtilsStreamable > {
 @public
  OrgMinimaObjectsBaseMiniNumber *mBlockTime_;
  OrgMinimaDatabaseMmrMMRSet *mParent_;
  OrgMinimaObjectsBaseMiniInteger *mEntryNumber_;
  JavaUtilArrayList *mEntries_;
  jint mMaxRow_;
  IOSObjectArray *mMaxEntries_;
  JavaUtilArrayList *mKeepers_;
  jboolean mFinalized_;
  OrgMinimaDatabaseMmrMMRData *mFinalizedRoot_;
  JavaUtilArrayList *mFinalizedPeaks_;
  JavaUtilArrayList *mFinalizedZeroRow_;
  jint MMR_HASH_BITS_;
}

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithInt:(jint)zBitLength;

- (instancetype)initWithOrgMinimaDatabaseMmrMMRSet:(OrgMinimaDatabaseMmrMMRSet *)zParent;

- (instancetype)initWithOrgMinimaDatabaseMmrMMRSet:(OrgMinimaDatabaseMmrMMRSet *)zParent
                                           withInt:(jint)zBitLength;

- (OrgMinimaDatabaseMmrMMREntry *)addExternalUnspentCoinWithOrgMinimaDatabaseMmrMMRProof:(OrgMinimaDatabaseMmrMMRProof *)zProof;

- (jboolean)addKeeperWithOrgMinimaObjectsBaseMiniInteger:(OrgMinimaObjectsBaseMiniInteger *)zEntry;

- (OrgMinimaDatabaseMmrMMREntry *)addUnspentCoinWithOrgMinimaDatabaseMmrMMRData:(OrgMinimaDatabaseMmrMMRData *)zData;

- (jboolean)checkProofWithOrgMinimaDatabaseMmrMMRProof:(OrgMinimaDatabaseMmrMMRProof *)zProof;

- (void)copyParentKeepers OBJC_METHOD_FAMILY_NONE;

- (void)finalizeSet;

- (OrgMinimaDatabaseMmrMMREntry *)findEntryWithOrgMinimaObjectsBaseMiniData:(OrgMinimaObjectsBaseMiniData *)zCoinID;

- (OrgMinimaObjectsBaseMiniNumber *)getBlockTime;

- (OrgMinimaDatabaseMmrMMRProof *)getFullProofToRootWithOrgMinimaObjectsBaseMiniInteger:(OrgMinimaObjectsBaseMiniInteger *)zEntry;

- (JavaUtilArrayList *)getKeepers;

- (jint)getMaxRow;

- (jint)getMaxRowWithBoolean:(jboolean)zCheckParent;

- (JavaUtilArrayList *)getMMRPeaks;

- (OrgMinimaDatabaseMmrMMRData *)getMMRRoot;

- (OrgMinimaDatabaseMmrMMRSet *)getParent;

- (OrgMinimaDatabaseMmrMMRSet *)getParentAtTimeWithOrgMinimaObjectsBaseMiniNumber:(OrgMinimaObjectsBaseMiniNumber *)zTime;

- (jint)getParentLength;

- (OrgMinimaDatabaseMmrMMRSet *)getPenultimateParent;

- (OrgMinimaDatabaseMmrMMRProof *)getProofWithOrgMinimaObjectsBaseMiniInteger:(OrgMinimaObjectsBaseMiniInteger *)zEntryNumber;

- (OrgMinimaDatabaseMmrMMRSet *)getRootParent;

- (JavaUtilArrayList *)getRowWithInt:(jint)zRow;

- (JavaUtilArrayList *)getZeroRow;

- (jboolean)isFinalized;

- (jboolean)isKeptAllreadyWithOrgMinimaObjectsBaseMiniInteger:(OrgMinimaObjectsBaseMiniInteger *)zNumber;

- (void)readDataStreamWithJavaIoDataInputStream:(JavaIoDataInputStream *)zIn;

- (OrgMinimaDatabaseMmrMMREntry *)searchAddressWithOrgMinimaObjectsBaseMiniData:(OrgMinimaObjectsBaseMiniData *)zAddress
                                             withOrgMinimaObjectsBaseMiniNumber:(OrgMinimaObjectsBaseMiniNumber *)zAmount
                                               withOrgMinimaObjectsBaseMiniData:(OrgMinimaObjectsBaseMiniData *)zTokenID;

- (void)setParentWithOrgMinimaDatabaseMmrMMRSet:(OrgMinimaDatabaseMmrMMRSet *)zParent;

- (OrgMinimaDatabaseMmrMMREntry *)updateSpentCoinWithOrgMinimaDatabaseMmrMMRProof:(OrgMinimaDatabaseMmrMMRProof *)zProof;

- (void)writeDataStreamWithJavaIoDataOutputStream:(JavaIoDataOutputStream *)zOut;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaDatabaseMmrMMRSet)

J2OBJC_FIELD_SETTER(OrgMinimaDatabaseMmrMMRSet, mBlockTime_, OrgMinimaObjectsBaseMiniNumber *)
J2OBJC_FIELD_SETTER(OrgMinimaDatabaseMmrMMRSet, mParent_, OrgMinimaDatabaseMmrMMRSet *)
J2OBJC_FIELD_SETTER(OrgMinimaDatabaseMmrMMRSet, mEntryNumber_, OrgMinimaObjectsBaseMiniInteger *)
J2OBJC_FIELD_SETTER(OrgMinimaDatabaseMmrMMRSet, mEntries_, JavaUtilArrayList *)
J2OBJC_FIELD_SETTER(OrgMinimaDatabaseMmrMMRSet, mMaxEntries_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(OrgMinimaDatabaseMmrMMRSet, mKeepers_, JavaUtilArrayList *)
J2OBJC_FIELD_SETTER(OrgMinimaDatabaseMmrMMRSet, mFinalizedRoot_, OrgMinimaDatabaseMmrMMRData *)
J2OBJC_FIELD_SETTER(OrgMinimaDatabaseMmrMMRSet, mFinalizedPeaks_, JavaUtilArrayList *)
J2OBJC_FIELD_SETTER(OrgMinimaDatabaseMmrMMRSet, mFinalizedZeroRow_, JavaUtilArrayList *)

FOUNDATION_EXPORT void OrgMinimaDatabaseMmrMMRSet_init(OrgMinimaDatabaseMmrMMRSet *self);

FOUNDATION_EXPORT OrgMinimaDatabaseMmrMMRSet *new_OrgMinimaDatabaseMmrMMRSet_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaDatabaseMmrMMRSet *create_OrgMinimaDatabaseMmrMMRSet_init(void);

FOUNDATION_EXPORT void OrgMinimaDatabaseMmrMMRSet_initWithInt_(OrgMinimaDatabaseMmrMMRSet *self, jint zBitLength);

FOUNDATION_EXPORT OrgMinimaDatabaseMmrMMRSet *new_OrgMinimaDatabaseMmrMMRSet_initWithInt_(jint zBitLength) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaDatabaseMmrMMRSet *create_OrgMinimaDatabaseMmrMMRSet_initWithInt_(jint zBitLength);

FOUNDATION_EXPORT void OrgMinimaDatabaseMmrMMRSet_initWithOrgMinimaDatabaseMmrMMRSet_(OrgMinimaDatabaseMmrMMRSet *self, OrgMinimaDatabaseMmrMMRSet *zParent);

FOUNDATION_EXPORT OrgMinimaDatabaseMmrMMRSet *new_OrgMinimaDatabaseMmrMMRSet_initWithOrgMinimaDatabaseMmrMMRSet_(OrgMinimaDatabaseMmrMMRSet *zParent) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaDatabaseMmrMMRSet *create_OrgMinimaDatabaseMmrMMRSet_initWithOrgMinimaDatabaseMmrMMRSet_(OrgMinimaDatabaseMmrMMRSet *zParent);

FOUNDATION_EXPORT void OrgMinimaDatabaseMmrMMRSet_initWithOrgMinimaDatabaseMmrMMRSet_withInt_(OrgMinimaDatabaseMmrMMRSet *self, OrgMinimaDatabaseMmrMMRSet *zParent, jint zBitLength);

FOUNDATION_EXPORT OrgMinimaDatabaseMmrMMRSet *new_OrgMinimaDatabaseMmrMMRSet_initWithOrgMinimaDatabaseMmrMMRSet_withInt_(OrgMinimaDatabaseMmrMMRSet *zParent, jint zBitLength) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaDatabaseMmrMMRSet *create_OrgMinimaDatabaseMmrMMRSet_initWithOrgMinimaDatabaseMmrMMRSet_withInt_(OrgMinimaDatabaseMmrMMRSet *zParent, jint zBitLength);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaDatabaseMmrMMRSet)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaDatabaseMmrMMRSet")
