//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/database/txpowdb/java/JavaDBRow.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaDatabaseTxpowdbJavaJavaDBRow")
#ifdef RESTRICT_OrgMinimaDatabaseTxpowdbJavaJavaDBRow
#define INCLUDE_ALL_OrgMinimaDatabaseTxpowdbJavaJavaDBRow 0
#else
#define INCLUDE_ALL_OrgMinimaDatabaseTxpowdbJavaJavaDBRow 1
#endif
#undef RESTRICT_OrgMinimaDatabaseTxpowdbJavaJavaDBRow

#if !defined (OrgMinimaDatabaseTxpowdbJavaJavaDBRow_) && (INCLUDE_ALL_OrgMinimaDatabaseTxpowdbJavaJavaDBRow || defined(INCLUDE_OrgMinimaDatabaseTxpowdbJavaJavaDBRow))
#define OrgMinimaDatabaseTxpowdbJavaJavaDBRow_

#define RESTRICT_OrgMinimaDatabaseTxpowdbTxPOWDBRow 1
#define INCLUDE_OrgMinimaDatabaseTxpowdbTxPOWDBRow 1
#include "org/minima/database/txpowdb/TxPOWDBRow.h"

@class OrgMinimaObjectsBaseMiniNumber;
@class OrgMinimaObjectsTxPOW;

@interface OrgMinimaDatabaseTxpowdbJavaJavaDBRow : NSObject < OrgMinimaDatabaseTxpowdbTxPOWDBRow >

#pragma mark Public

- (instancetype)initWithOrgMinimaObjectsTxPOW:(OrgMinimaObjectsTxPOW *)zTxPOW;

- (void)deleteRow;

- (jint)getBlockState;

- (jlong)getDeleteTime;

- (OrgMinimaObjectsBaseMiniNumber *)getInBlockNumber;

- (NSString *)getStatusAsString;

- (OrgMinimaObjectsTxPOW *)getTxPOW;

- (jboolean)isInBlock;

- (jboolean)isOnChainBlock;

- (void)setBlockStateWithInt:(jint)zState;

- (void)setInBlockNumberWithOrgMinimaObjectsBaseMiniNumber:(OrgMinimaObjectsBaseMiniNumber *)zBlockNumber;

- (void)setIsInBlockWithBoolean:(jboolean)zIsInBlock;

- (void)setOnChainBlockWithBoolean:(jboolean)zOnChain;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaDatabaseTxpowdbJavaJavaDBRow)

FOUNDATION_EXPORT void OrgMinimaDatabaseTxpowdbJavaJavaDBRow_initWithOrgMinimaObjectsTxPOW_(OrgMinimaDatabaseTxpowdbJavaJavaDBRow *self, OrgMinimaObjectsTxPOW *zTxPOW);

FOUNDATION_EXPORT OrgMinimaDatabaseTxpowdbJavaJavaDBRow *new_OrgMinimaDatabaseTxpowdbJavaJavaDBRow_initWithOrgMinimaObjectsTxPOW_(OrgMinimaObjectsTxPOW *zTxPOW) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaDatabaseTxpowdbJavaJavaDBRow *create_OrgMinimaDatabaseTxpowdbJavaJavaDBRow_initWithOrgMinimaObjectsTxPOW_(OrgMinimaObjectsTxPOW *zTxPOW);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaDatabaseTxpowdbJavaJavaDBRow)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaDatabaseTxpowdbJavaJavaDBRow")
