//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/kissvm/functions/state/SAMESTATE.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaKissvmFunctionsStateSAMESTATE")
#ifdef RESTRICT_OrgMinimaKissvmFunctionsStateSAMESTATE
#define INCLUDE_ALL_OrgMinimaKissvmFunctionsStateSAMESTATE 0
#else
#define INCLUDE_ALL_OrgMinimaKissvmFunctionsStateSAMESTATE 1
#endif
#undef RESTRICT_OrgMinimaKissvmFunctionsStateSAMESTATE

#if !defined (OrgMinimaKissvmFunctionsStateSAMESTATE_) && (INCLUDE_ALL_OrgMinimaKissvmFunctionsStateSAMESTATE || defined(INCLUDE_OrgMinimaKissvmFunctionsStateSAMESTATE))
#define OrgMinimaKissvmFunctionsStateSAMESTATE_

#define RESTRICT_OrgMinimaKissvmFunctionsMinimaFunction 1
#define INCLUDE_OrgMinimaKissvmFunctionsMinimaFunction 1
#include "org/minima/kissvm/functions/MinimaFunction.h"

@class OrgMinimaKissvmContract;
@class OrgMinimaKissvmValuesValue;

@interface OrgMinimaKissvmFunctionsStateSAMESTATE : OrgMinimaKissvmFunctionsMinimaFunction

#pragma mark Public

- (instancetype)init;

- (OrgMinimaKissvmFunctionsMinimaFunction *)getNewFunction;

- (OrgMinimaKissvmValuesValue *)runFunctionWithOrgMinimaKissvmContract:(OrgMinimaKissvmContract *)zContract;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaKissvmFunctionsStateSAMESTATE)

FOUNDATION_EXPORT void OrgMinimaKissvmFunctionsStateSAMESTATE_init(OrgMinimaKissvmFunctionsStateSAMESTATE *self);

FOUNDATION_EXPORT OrgMinimaKissvmFunctionsStateSAMESTATE *new_OrgMinimaKissvmFunctionsStateSAMESTATE_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaKissvmFunctionsStateSAMESTATE *create_OrgMinimaKissvmFunctionsStateSAMESTATE_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaKissvmFunctionsStateSAMESTATE)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaKissvmFunctionsStateSAMESTATE")
