//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/kissvm/functions/state/STATE.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaKissvmFunctionsStateSTATE")
#ifdef RESTRICT_OrgMinimaKissvmFunctionsStateSTATE
#define INCLUDE_ALL_OrgMinimaKissvmFunctionsStateSTATE 0
#else
#define INCLUDE_ALL_OrgMinimaKissvmFunctionsStateSTATE 1
#endif
#undef RESTRICT_OrgMinimaKissvmFunctionsStateSTATE

#if !defined (OrgMinimaKissvmFunctionsStateSTATE_) && (INCLUDE_ALL_OrgMinimaKissvmFunctionsStateSTATE || defined(INCLUDE_OrgMinimaKissvmFunctionsStateSTATE))
#define OrgMinimaKissvmFunctionsStateSTATE_

#define RESTRICT_OrgMinimaKissvmFunctionsMinimaFunction 1
#define INCLUDE_OrgMinimaKissvmFunctionsMinimaFunction 1
#include "org/minima/kissvm/functions/MinimaFunction.h"

@class OrgMinimaKissvmContract;
@class OrgMinimaKissvmValuesValue;

@interface OrgMinimaKissvmFunctionsStateSTATE : OrgMinimaKissvmFunctionsMinimaFunction

#pragma mark Public

- (instancetype)init;

- (OrgMinimaKissvmFunctionsMinimaFunction *)getNewFunction;

- (OrgMinimaKissvmValuesValue *)runFunctionWithOrgMinimaKissvmContract:(OrgMinimaKissvmContract *)zContract;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaKissvmFunctionsStateSTATE)

FOUNDATION_EXPORT void OrgMinimaKissvmFunctionsStateSTATE_init(OrgMinimaKissvmFunctionsStateSTATE *self);

FOUNDATION_EXPORT OrgMinimaKissvmFunctionsStateSTATE *new_OrgMinimaKissvmFunctionsStateSTATE_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaKissvmFunctionsStateSTATE *create_OrgMinimaKissvmFunctionsStateSTATE_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaKissvmFunctionsStateSTATE)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaKissvmFunctionsStateSTATE")
