//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/kissvm/functions/cast/SCRIPT.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaKissvmFunctionsCastSCRIPT")
#ifdef RESTRICT_OrgMinimaKissvmFunctionsCastSCRIPT
#define INCLUDE_ALL_OrgMinimaKissvmFunctionsCastSCRIPT 0
#else
#define INCLUDE_ALL_OrgMinimaKissvmFunctionsCastSCRIPT 1
#endif
#undef RESTRICT_OrgMinimaKissvmFunctionsCastSCRIPT

#if !defined (OrgMinimaKissvmFunctionsCastSCRIPT_) && (INCLUDE_ALL_OrgMinimaKissvmFunctionsCastSCRIPT || defined(INCLUDE_OrgMinimaKissvmFunctionsCastSCRIPT))
#define OrgMinimaKissvmFunctionsCastSCRIPT_

#define RESTRICT_OrgMinimaKissvmFunctionsMinimaFunction 1
#define INCLUDE_OrgMinimaKissvmFunctionsMinimaFunction 1
#include "org/minima/kissvm/functions/MinimaFunction.h"

@class OrgMinimaKissvmContract;
@class OrgMinimaKissvmValuesValue;

@interface OrgMinimaKissvmFunctionsCastSCRIPT : OrgMinimaKissvmFunctionsMinimaFunction

#pragma mark Public

- (instancetype)init;

- (OrgMinimaKissvmFunctionsMinimaFunction *)getNewFunction;

- (OrgMinimaKissvmValuesValue *)runFunctionWithOrgMinimaKissvmContract:(OrgMinimaKissvmContract *)zContract;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaKissvmFunctionsCastSCRIPT)

FOUNDATION_EXPORT void OrgMinimaKissvmFunctionsCastSCRIPT_init(OrgMinimaKissvmFunctionsCastSCRIPT *self);

FOUNDATION_EXPORT OrgMinimaKissvmFunctionsCastSCRIPT *new_OrgMinimaKissvmFunctionsCastSCRIPT_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaKissvmFunctionsCastSCRIPT *create_OrgMinimaKissvmFunctionsCastSCRIPT_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaKissvmFunctionsCastSCRIPT)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaKissvmFunctionsCastSCRIPT")
