//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/miniscript/functions/sha/CHAINSHA.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaMiniscriptFunctionsShaCHAINSHA")
#ifdef RESTRICT_OrgMinimaMiniscriptFunctionsShaCHAINSHA
#define INCLUDE_ALL_OrgMinimaMiniscriptFunctionsShaCHAINSHA 0
#else
#define INCLUDE_ALL_OrgMinimaMiniscriptFunctionsShaCHAINSHA 1
#endif
#undef RESTRICT_OrgMinimaMiniscriptFunctionsShaCHAINSHA

#if !defined (OrgMinimaMiniscriptFunctionsShaCHAINSHA_) && (INCLUDE_ALL_OrgMinimaMiniscriptFunctionsShaCHAINSHA || defined(INCLUDE_OrgMinimaMiniscriptFunctionsShaCHAINSHA))
#define OrgMinimaMiniscriptFunctionsShaCHAINSHA_

#define RESTRICT_OrgMinimaMiniscriptFunctionsMinimaFunction 1
#define INCLUDE_OrgMinimaMiniscriptFunctionsMinimaFunction 1
#include "org/minima/miniscript/functions/MinimaFunction.h"

@class OrgMinimaMiniscriptContract;
@class OrgMinimaMiniscriptValuesValue;

@interface OrgMinimaMiniscriptFunctionsShaCHAINSHA : OrgMinimaMiniscriptFunctionsMinimaFunction

#pragma mark Public

- (instancetype)init;

- (OrgMinimaMiniscriptFunctionsMinimaFunction *)getNewFunction;

- (OrgMinimaMiniscriptValuesValue *)runFunctionWithOrgMinimaMiniscriptContract:(OrgMinimaMiniscriptContract *)zContract;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaMiniscriptFunctionsShaCHAINSHA)

FOUNDATION_EXPORT void OrgMinimaMiniscriptFunctionsShaCHAINSHA_init(OrgMinimaMiniscriptFunctionsShaCHAINSHA *self);

FOUNDATION_EXPORT OrgMinimaMiniscriptFunctionsShaCHAINSHA *new_OrgMinimaMiniscriptFunctionsShaCHAINSHA_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaMiniscriptFunctionsShaCHAINSHA *create_OrgMinimaMiniscriptFunctionsShaCHAINSHA_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaMiniscriptFunctionsShaCHAINSHA)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaMiniscriptFunctionsShaCHAINSHA")
