//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/miniscript/functions/sha/SHA3.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaMiniscriptFunctionsShaSHA3")
#ifdef RESTRICT_OrgMinimaMiniscriptFunctionsShaSHA3
#define INCLUDE_ALL_OrgMinimaMiniscriptFunctionsShaSHA3 0
#else
#define INCLUDE_ALL_OrgMinimaMiniscriptFunctionsShaSHA3 1
#endif
#undef RESTRICT_OrgMinimaMiniscriptFunctionsShaSHA3

#if !defined (OrgMinimaMiniscriptFunctionsShaSHA3_) && (INCLUDE_ALL_OrgMinimaMiniscriptFunctionsShaSHA3 || defined(INCLUDE_OrgMinimaMiniscriptFunctionsShaSHA3))
#define OrgMinimaMiniscriptFunctionsShaSHA3_

#define RESTRICT_OrgMinimaMiniscriptFunctionsMinimaFunction 1
#define INCLUDE_OrgMinimaMiniscriptFunctionsMinimaFunction 1
#include "org/minima/miniscript/functions/MinimaFunction.h"

@class OrgMinimaMiniscriptContract;
@class OrgMinimaMiniscriptValuesValue;

@interface OrgMinimaMiniscriptFunctionsShaSHA3 : OrgMinimaMiniscriptFunctionsMinimaFunction

#pragma mark Public

- (instancetype)init;

- (OrgMinimaMiniscriptFunctionsMinimaFunction *)getNewFunction;

- (OrgMinimaMiniscriptValuesValue *)runFunctionWithOrgMinimaMiniscriptContract:(OrgMinimaMiniscriptContract *)zContract;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaMiniscriptFunctionsShaSHA3)

FOUNDATION_EXPORT void OrgMinimaMiniscriptFunctionsShaSHA3_init(OrgMinimaMiniscriptFunctionsShaSHA3 *self);

FOUNDATION_EXPORT OrgMinimaMiniscriptFunctionsShaSHA3 *new_OrgMinimaMiniscriptFunctionsShaSHA3_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaMiniscriptFunctionsShaSHA3 *create_OrgMinimaMiniscriptFunctionsShaSHA3_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaMiniscriptFunctionsShaSHA3)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaMiniscriptFunctionsShaSHA3")
