//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/system/brains/ConsensusTxn.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaSystemBrainsConsensusTxn")
#ifdef RESTRICT_OrgMinimaSystemBrainsConsensusTxn
#define INCLUDE_ALL_OrgMinimaSystemBrainsConsensusTxn 0
#else
#define INCLUDE_ALL_OrgMinimaSystemBrainsConsensusTxn 1
#endif
#undef RESTRICT_OrgMinimaSystemBrainsConsensusTxn

#if !defined (OrgMinimaSystemBrainsConsensusTxn_) && (INCLUDE_ALL_OrgMinimaSystemBrainsConsensusTxn || defined(INCLUDE_OrgMinimaSystemBrainsConsensusTxn))
#define OrgMinimaSystemBrainsConsensusTxn_

@class OrgMinimaDatabaseMinimaDB;
@class OrgMinimaSystemBrainsConsensusHandler;
@class OrgMinimaUtilsMessagesMessage;

@interface OrgMinimaSystemBrainsConsensusTxn : NSObject {
 @public
  OrgMinimaDatabaseMinimaDB *mDB_;
  OrgMinimaSystemBrainsConsensusHandler *mHandler_;
}

#pragma mark Public

- (instancetype)initWithOrgMinimaDatabaseMinimaDB:(OrgMinimaDatabaseMinimaDB *)zDB
        withOrgMinimaSystemBrainsConsensusHandler:(OrgMinimaSystemBrainsConsensusHandler *)zHandler;

- (void)processMessageWithOrgMinimaUtilsMessagesMessage:(OrgMinimaUtilsMessagesMessage *)zMessage;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaSystemBrainsConsensusTxn)

J2OBJC_FIELD_SETTER(OrgMinimaSystemBrainsConsensusTxn, mDB_, OrgMinimaDatabaseMinimaDB *)
J2OBJC_FIELD_SETTER(OrgMinimaSystemBrainsConsensusTxn, mHandler_, OrgMinimaSystemBrainsConsensusHandler *)

inline NSString *OrgMinimaSystemBrainsConsensusTxn_get_CONSENSUS_PREFIX(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgMinimaSystemBrainsConsensusTxn_CONSENSUS_PREFIX;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgMinimaSystemBrainsConsensusTxn, CONSENSUS_PREFIX, NSString *)

inline NSString *OrgMinimaSystemBrainsConsensusTxn_get_CONSENSUS_TXNCREATE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgMinimaSystemBrainsConsensusTxn_CONSENSUS_TXNCREATE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgMinimaSystemBrainsConsensusTxn, CONSENSUS_TXNCREATE, NSString *)

inline NSString *OrgMinimaSystemBrainsConsensusTxn_get_CONSENSUS_TXNDELETE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgMinimaSystemBrainsConsensusTxn_CONSENSUS_TXNDELETE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgMinimaSystemBrainsConsensusTxn, CONSENSUS_TXNDELETE, NSString *)

inline NSString *OrgMinimaSystemBrainsConsensusTxn_get_CONSENSUS_TXNLIST(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgMinimaSystemBrainsConsensusTxn_CONSENSUS_TXNLIST;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgMinimaSystemBrainsConsensusTxn, CONSENSUS_TXNLIST, NSString *)

inline NSString *OrgMinimaSystemBrainsConsensusTxn_get_CONSENSUS_TXNAUTO(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgMinimaSystemBrainsConsensusTxn_CONSENSUS_TXNAUTO;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgMinimaSystemBrainsConsensusTxn, CONSENSUS_TXNAUTO, NSString *)

inline NSString *OrgMinimaSystemBrainsConsensusTxn_get_CONSENSUS_TXNINPUT(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgMinimaSystemBrainsConsensusTxn_CONSENSUS_TXNINPUT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgMinimaSystemBrainsConsensusTxn, CONSENSUS_TXNINPUT, NSString *)

inline NSString *OrgMinimaSystemBrainsConsensusTxn_get_CONSENSUS_TXNOUTPUT(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgMinimaSystemBrainsConsensusTxn_CONSENSUS_TXNOUTPUT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgMinimaSystemBrainsConsensusTxn, CONSENSUS_TXNOUTPUT, NSString *)

inline NSString *OrgMinimaSystemBrainsConsensusTxn_get_CONSENSUS_TXNSTATEVAR(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgMinimaSystemBrainsConsensusTxn_CONSENSUS_TXNSTATEVAR;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgMinimaSystemBrainsConsensusTxn, CONSENSUS_TXNSTATEVAR, NSString *)

inline NSString *OrgMinimaSystemBrainsConsensusTxn_get_CONSENSUS_TXNSIGN(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgMinimaSystemBrainsConsensusTxn_CONSENSUS_TXNSIGN;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgMinimaSystemBrainsConsensusTxn, CONSENSUS_TXNSIGN, NSString *)

inline NSString *OrgMinimaSystemBrainsConsensusTxn_get_CONSENSUS_TXNVALIDATE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgMinimaSystemBrainsConsensusTxn_CONSENSUS_TXNVALIDATE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgMinimaSystemBrainsConsensusTxn, CONSENSUS_TXNVALIDATE, NSString *)

inline NSString *OrgMinimaSystemBrainsConsensusTxn_get_CONSENSUS_TXNSCRIPT(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgMinimaSystemBrainsConsensusTxn_CONSENSUS_TXNSCRIPT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgMinimaSystemBrainsConsensusTxn, CONSENSUS_TXNSCRIPT, NSString *)

inline NSString *OrgMinimaSystemBrainsConsensusTxn_get_CONSENSUS_TXNPOST(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgMinimaSystemBrainsConsensusTxn_CONSENSUS_TXNPOST;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgMinimaSystemBrainsConsensusTxn, CONSENSUS_TXNPOST, NSString *)

inline NSString *OrgMinimaSystemBrainsConsensusTxn_get_CONSENSUS_TXNEXPORT(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgMinimaSystemBrainsConsensusTxn_CONSENSUS_TXNEXPORT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgMinimaSystemBrainsConsensusTxn, CONSENSUS_TXNEXPORT, NSString *)

inline NSString *OrgMinimaSystemBrainsConsensusTxn_get_CONSENSUS_TXNIMPORT(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgMinimaSystemBrainsConsensusTxn_CONSENSUS_TXNIMPORT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgMinimaSystemBrainsConsensusTxn, CONSENSUS_TXNIMPORT, NSString *)

FOUNDATION_EXPORT void OrgMinimaSystemBrainsConsensusTxn_initWithOrgMinimaDatabaseMinimaDB_withOrgMinimaSystemBrainsConsensusHandler_(OrgMinimaSystemBrainsConsensusTxn *self, OrgMinimaDatabaseMinimaDB *zDB, OrgMinimaSystemBrainsConsensusHandler *zHandler);

FOUNDATION_EXPORT OrgMinimaSystemBrainsConsensusTxn *new_OrgMinimaSystemBrainsConsensusTxn_initWithOrgMinimaDatabaseMinimaDB_withOrgMinimaSystemBrainsConsensusHandler_(OrgMinimaDatabaseMinimaDB *zDB, OrgMinimaSystemBrainsConsensusHandler *zHandler) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaSystemBrainsConsensusTxn *create_OrgMinimaSystemBrainsConsensusTxn_initWithOrgMinimaDatabaseMinimaDB_withOrgMinimaSystemBrainsConsensusHandler_(OrgMinimaDatabaseMinimaDB *zDB, OrgMinimaSystemBrainsConsensusHandler *zHandler);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaSystemBrainsConsensusTxn)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaSystemBrainsConsensusTxn")
