//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/kissvm/statements/StatementParser.java
//

#include "J2ObjC_source.h"
#include "java/util/ArrayList.h"
#include "java/util/List.h"
#include "org/minima/kissvm/exceptions/MinimaParseException.h"
#include "org/minima/kissvm/expressions/ConstantExpression.h"
#include "org/minima/kissvm/expressions/Expression.h"
#include "org/minima/kissvm/expressions/ExpressionParser.h"
#include "org/minima/kissvm/statements/StatementBlock.h"
#include "org/minima/kissvm/statements/StatementParser.h"
#include "org/minima/kissvm/statements/commands/ASSERTstatement.h"
#include "org/minima/kissvm/statements/commands/EXECstatement.h"
#include "org/minima/kissvm/statements/commands/IFstatement.h"
#include "org/minima/kissvm/statements/commands/LETstatement.h"
#include "org/minima/kissvm/statements/commands/MASTstatement.h"
#include "org/minima/kissvm/statements/commands/RETURNstatement.h"
#include "org/minima/kissvm/statements/commands/WHILEstatement.h"
#include "org/minima/kissvm/tokens/LexicalTokenizer.h"
#include "org/minima/kissvm/tokens/Token.h"
#include "org/minima/kissvm/values/BooleanValue.h"

@interface OrgMinimaKissvmStatementsStatementParser ()

+ (id<JavaUtilList>)getElseOrElseIfOrEndIFWithJavaUtilList:(id<JavaUtilList>)zTokens
                                                   withInt:(jint)zCurrentPosition
                                               withBoolean:(jboolean)zElseAlso;

+ (id<JavaUtilList>)getEndWHILEWithJavaUtilList:(id<JavaUtilList>)zTokens
                                        withInt:(jint)zCurrentPosition;

+ (id<JavaUtilList>)getTokensToNextCommandWithJavaUtilList:(id<JavaUtilList>)zTokens
                                                   withInt:(jint)zCurrentPosition;

+ (id<JavaUtilList>)getTokensToNextEqualsWithJavaUtilList:(id<JavaUtilList>)zTokens
                                                  withInt:(jint)zCurrentPosition;

@end

__attribute__((unused)) static id<JavaUtilList> OrgMinimaKissvmStatementsStatementParser_getElseOrElseIfOrEndIFWithJavaUtilList_withInt_withBoolean_(id<JavaUtilList> zTokens, jint zCurrentPosition, jboolean zElseAlso);

__attribute__((unused)) static id<JavaUtilList> OrgMinimaKissvmStatementsStatementParser_getEndWHILEWithJavaUtilList_withInt_(id<JavaUtilList> zTokens, jint zCurrentPosition);

__attribute__((unused)) static id<JavaUtilList> OrgMinimaKissvmStatementsStatementParser_getTokensToNextCommandWithJavaUtilList_withInt_(id<JavaUtilList> zTokens, jint zCurrentPosition);

__attribute__((unused)) static id<JavaUtilList> OrgMinimaKissvmStatementsStatementParser_getTokensToNextEqualsWithJavaUtilList_withInt_(id<JavaUtilList> zTokens, jint zCurrentPosition);

@implementation OrgMinimaKissvmStatementsStatementParser

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgMinimaKissvmStatementsStatementParser_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (OrgMinimaKissvmStatementsStatementBlock *)parseTokensWithJavaUtilList:(id<JavaUtilList>)zTokens {
  return OrgMinimaKissvmStatementsStatementParser_parseTokensWithJavaUtilList_(zTokens);
}

+ (id<JavaUtilList>)getElseOrElseIfOrEndIFWithJavaUtilList:(id<JavaUtilList>)zTokens
                                                   withInt:(jint)zCurrentPosition
                                               withBoolean:(jboolean)zElseAlso {
  return OrgMinimaKissvmStatementsStatementParser_getElseOrElseIfOrEndIFWithJavaUtilList_withInt_withBoolean_(zTokens, zCurrentPosition, zElseAlso);
}

+ (id<JavaUtilList>)getEndWHILEWithJavaUtilList:(id<JavaUtilList>)zTokens
                                        withInt:(jint)zCurrentPosition {
  return OrgMinimaKissvmStatementsStatementParser_getEndWHILEWithJavaUtilList_withInt_(zTokens, zCurrentPosition);
}

+ (id<JavaUtilList>)getTokensToNextCommandWithJavaUtilList:(id<JavaUtilList>)zTokens
                                                   withInt:(jint)zCurrentPosition {
  return OrgMinimaKissvmStatementsStatementParser_getTokensToNextCommandWithJavaUtilList_withInt_(zTokens, zCurrentPosition);
}

+ (id<JavaUtilList>)getTokensToNextEqualsWithJavaUtilList:(id<JavaUtilList>)zTokens
                                                  withInt:(jint)zCurrentPosition {
  return OrgMinimaKissvmStatementsStatementParser_getTokensToNextEqualsWithJavaUtilList_withInt_(zTokens, zCurrentPosition);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LOrgMinimaKissvmStatementsStatementBlock;", 0x9, 0, 1, 2, 3, -1, -1 },
    { NULL, "LJavaUtilList;", 0xa, 4, 5, -1, 6, -1, -1 },
    { NULL, "LJavaUtilList;", 0xa, 7, 8, -1, 9, -1, -1 },
    { NULL, "LJavaUtilList;", 0xa, 10, 8, -1, 9, -1, -1 },
    { NULL, "LJavaUtilList;", 0xa, 11, 8, -1, 9, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(parseTokensWithJavaUtilList:);
  methods[2].selector = @selector(getElseOrElseIfOrEndIFWithJavaUtilList:withInt:withBoolean:);
  methods[3].selector = @selector(getEndWHILEWithJavaUtilList:withInt:);
  methods[4].selector = @selector(getTokensToNextCommandWithJavaUtilList:withInt:);
  methods[5].selector = @selector(getTokensToNextEqualsWithJavaUtilList:withInt:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "parseTokens", "LJavaUtilList;", "LOrgMinimaKissvmExceptionsMinimaParseException;", "(Ljava/util/List<Lorg/minima/kissvm/tokens/Token;>;)Lorg/minima/kissvm/statements/StatementBlock;", "getElseOrElseIfOrEndIF", "LJavaUtilList;IZ", "(Ljava/util/List<Lorg/minima/kissvm/tokens/Token;>;IZ)Ljava/util/List<Lorg/minima/kissvm/tokens/Token;>;", "getEndWHILE", "LJavaUtilList;I", "(Ljava/util/List<Lorg/minima/kissvm/tokens/Token;>;I)Ljava/util/List<Lorg/minima/kissvm/tokens/Token;>;", "getTokensToNextCommand", "getTokensToNextEquals" };
  static const J2ObjcClassInfo _OrgMinimaKissvmStatementsStatementParser = { "StatementParser", "org.minima.kissvm.statements", ptrTable, methods, NULL, 7, 0x1, 6, 0, -1, -1, -1, -1, -1 };
  return &_OrgMinimaKissvmStatementsStatementParser;
}

@end

void OrgMinimaKissvmStatementsStatementParser_init(OrgMinimaKissvmStatementsStatementParser *self) {
  NSObject_init(self);
}

OrgMinimaKissvmStatementsStatementParser *new_OrgMinimaKissvmStatementsStatementParser_init() {
  J2OBJC_NEW_IMPL(OrgMinimaKissvmStatementsStatementParser, init)
}

OrgMinimaKissvmStatementsStatementParser *create_OrgMinimaKissvmStatementsStatementParser_init() {
  J2OBJC_CREATE_IMPL(OrgMinimaKissvmStatementsStatementParser, init)
}

OrgMinimaKissvmStatementsStatementBlock *OrgMinimaKissvmStatementsStatementParser_parseTokensWithJavaUtilList_(id<JavaUtilList> zTokens) {
  OrgMinimaKissvmStatementsStatementParser_initialize();
  id<JavaUtilList> stats = new_JavaUtilArrayList_init();
  jint currentPosition = 0;
  jint totaltokens = [((id<JavaUtilList>) nil_chk(zTokens)) size];
  while (currentPosition < totaltokens) {
    OrgMinimaKissvmTokensToken *tok = [zTokens getWithInt:currentPosition++];
    NSString *token = [((OrgMinimaKissvmTokensToken *) nil_chk(tok)) getToken];
    jint type = [tok getTokenType];
    if (type != OrgMinimaKissvmTokensToken_TOKEN_COMMAND) {
      @throw new_OrgMinimaKissvmExceptionsMinimaParseException_initWithNSString_(JreStrcat("$$", @"Invalid Token where there should be a COMMMAND - ", token));
    }
    if ([((NSString *) nil_chk(token)) java_equalsIgnoreCase:@"LET"]) {
      OrgMinimaKissvmTokensToken *var = [zTokens getWithInt:currentPosition++];
      if ([((OrgMinimaKissvmTokensToken *) nil_chk(var)) getTokenType] == OrgMinimaKissvmTokensToken_TOKEN_OPENBRACKET) {
        id<JavaUtilList> arraypos = OrgMinimaKissvmStatementsStatementParser_getTokensToNextEqualsWithJavaUtilList_withInt_(zTokens, currentPosition);
        currentPosition += [((id<JavaUtilList>) nil_chk(arraypos)) size];
        jint arrsize = [arraypos size];
        var = [arraypos getWithInt:arrsize - 1];
        if ([((OrgMinimaKissvmTokensToken *) nil_chk(var)) getTokenType] != OrgMinimaKissvmTokensToken_TOKEN_CLOSEBRACKET) {
          @throw new_OrgMinimaKissvmExceptionsMinimaParseException_initWithNSString_(JreStrcat("$$C", @"Incorrect LET statement, missing ) .. ", [var getToken], ')'));
        }
        var = [zTokens getWithInt:currentPosition++];
        if ([((OrgMinimaKissvmTokensToken *) nil_chk(var)) getTokenType] != OrgMinimaKissvmTokensToken_TOKEN_OPERATOR && ![((NSString *) nil_chk([var getToken])) isEqual:@"="]) {
          @throw new_OrgMinimaKissvmExceptionsMinimaParseException_initWithNSString_(JreStrcat("$$C", @"Incorrect LET statement, missing = (..", [var getToken], ')'));
        }
        (void) [arraypos removeWithInt:arrsize - 1];
        OrgMinimaKissvmTokensLexicalTokenizer *lt = new_OrgMinimaKissvmTokensLexicalTokenizer_initWithJavaUtilList_(arraypos);
        JavaUtilArrayList *exps = new_JavaUtilArrayList_init();
        while (![lt checkAllTokensUsed]) {
          id<OrgMinimaKissvmExpressionsExpression> letexp = OrgMinimaKissvmExpressionsExpressionParser_getExpressionWithOrgMinimaKissvmTokensLexicalTokenizer_(lt);
          [exps addWithId:letexp];
        }
        id<JavaUtilList> lettokens = OrgMinimaKissvmStatementsStatementParser_getTokensToNextCommandWithJavaUtilList_withInt_(zTokens, currentPosition);
        currentPosition += [((id<JavaUtilList>) nil_chk(lettokens)) size];
        id<OrgMinimaKissvmExpressionsExpression> exp = OrgMinimaKissvmExpressionsExpressionParser_getExpressionWithJavaUtilList_(lettokens);
        [stats addWithId:new_OrgMinimaKissvmStatementsCommandsLETstatement_initWithJavaUtilArrayList_withOrgMinimaKissvmExpressionsExpression_(exps, exp)];
      }
      else if ([var getTokenType] == OrgMinimaKissvmTokensToken_TOKEN_VARIABLE) {
        NSString *varname = [var getToken];
        var = [zTokens getWithInt:currentPosition++];
        if ([((OrgMinimaKissvmTokensToken *) nil_chk(var)) getTokenType] != OrgMinimaKissvmTokensToken_TOKEN_OPERATOR && ![((NSString *) nil_chk([var getToken])) isEqual:@"="]) {
          @throw new_OrgMinimaKissvmExceptionsMinimaParseException_initWithNSString_(JreStrcat("$$C", @"Incorrect LET statement, missing = (..", [var getToken], ')'));
        }
        id<JavaUtilList> lettokens = OrgMinimaKissvmStatementsStatementParser_getTokensToNextCommandWithJavaUtilList_withInt_(zTokens, currentPosition);
        currentPosition += [((id<JavaUtilList>) nil_chk(lettokens)) size];
        id<OrgMinimaKissvmExpressionsExpression> exp = OrgMinimaKissvmExpressionsExpressionParser_getExpressionWithJavaUtilList_(lettokens);
        [stats addWithId:new_OrgMinimaKissvmStatementsCommandsLETstatement_initWithNSString_withOrgMinimaKissvmExpressionsExpression_(varname, exp)];
      }
      else {
        @throw new_OrgMinimaKissvmExceptionsMinimaParseException_initWithNSString_(JreStrcat("$$C", @"Not a variable or array after LET (..", [var getToken], ')'));
      }
    }
    else if ([token java_equalsIgnoreCase:@"EXEC"]) {
      id<JavaUtilList> exectokens = OrgMinimaKissvmStatementsStatementParser_getTokensToNextCommandWithJavaUtilList_withInt_(zTokens, currentPosition);
      currentPosition += [((id<JavaUtilList>) nil_chk(exectokens)) size];
      id<OrgMinimaKissvmExpressionsExpression> exp = OrgMinimaKissvmExpressionsExpressionParser_getExpressionWithJavaUtilList_(exectokens);
      [stats addWithId:new_OrgMinimaKissvmStatementsCommandsEXECstatement_initWithOrgMinimaKissvmExpressionsExpression_(exp)];
    }
    else if ([token java_equalsIgnoreCase:@"MAST"]) {
      id<JavaUtilList> masttokens = OrgMinimaKissvmStatementsStatementParser_getTokensToNextCommandWithJavaUtilList_withInt_(zTokens, currentPosition);
      currentPosition += [((id<JavaUtilList>) nil_chk(masttokens)) size];
      id<OrgMinimaKissvmExpressionsExpression> exp = OrgMinimaKissvmExpressionsExpressionParser_getExpressionWithJavaUtilList_(masttokens);
      [stats addWithId:new_OrgMinimaKissvmStatementsCommandsMASTstatement_initWithOrgMinimaKissvmExpressionsExpression_(exp)];
    }
    else if ([token java_equalsIgnoreCase:@"IF"]) {
      OrgMinimaKissvmStatementsCommandsIFstatement *ifsx = new_OrgMinimaKissvmStatementsCommandsIFstatement_init();
      id<JavaUtilList> conditiontokens = OrgMinimaKissvmStatementsStatementParser_getTokensToNextCommandWithJavaUtilList_withInt_(zTokens, currentPosition);
      id<OrgMinimaKissvmExpressionsExpression> IFcondition = OrgMinimaKissvmExpressionsExpressionParser_getExpressionWithJavaUtilList_(conditiontokens);
      currentPosition += [((id<JavaUtilList>) nil_chk(conditiontokens)) size] + 1;
      id<JavaUtilList> actiontokens = OrgMinimaKissvmStatementsStatementParser_getElseOrElseIfOrEndIFWithJavaUtilList_withInt_withBoolean_(zTokens, currentPosition, true);
      currentPosition += [((id<JavaUtilList>) nil_chk(actiontokens)) size];
      NSString *nexttok = [((OrgMinimaKissvmTokensToken *) nil_chk([actiontokens getWithInt:[actiontokens size] - 1])) getToken];
      actiontokens = [actiontokens subListWithInt:0 withInt:[actiontokens size] - 1];
      OrgMinimaKissvmStatementsStatementBlock *IFaction = OrgMinimaKissvmStatementsStatementParser_parseTokensWithJavaUtilList_(actiontokens);
      [ifsx addConditionWithOrgMinimaKissvmExpressionsExpression:IFcondition withOrgMinimaKissvmStatementsStatementBlock:IFaction];
      while (![((NSString *) nil_chk(nexttok)) isEqual:@"ENDIF"]) {
        id<OrgMinimaKissvmExpressionsExpression> ELSEcondition = nil;
        OrgMinimaKissvmStatementsStatementBlock *ELSEaction = nil;
        if ([nexttok isEqual:@"ELSE"]) {
          ELSEcondition = new_OrgMinimaKissvmExpressionsConstantExpression_initWithOrgMinimaKissvmValuesValue_(JreLoadStatic(OrgMinimaKissvmValuesBooleanValue, TRUE));
        }
        else {
          conditiontokens = OrgMinimaKissvmStatementsStatementParser_getTokensToNextCommandWithJavaUtilList_withInt_(zTokens, currentPosition);
          ELSEcondition = OrgMinimaKissvmExpressionsExpressionParser_getExpressionWithJavaUtilList_(conditiontokens);
          currentPosition += [((id<JavaUtilList>) nil_chk(conditiontokens)) size] + 1;
        }
        actiontokens = OrgMinimaKissvmStatementsStatementParser_getElseOrElseIfOrEndIFWithJavaUtilList_withInt_withBoolean_(zTokens, currentPosition, true);
        currentPosition += [((id<JavaUtilList>) nil_chk(actiontokens)) size];
        nexttok = [((OrgMinimaKissvmTokensToken *) nil_chk([actiontokens getWithInt:[actiontokens size] - 1])) getToken];
        actiontokens = [actiontokens subListWithInt:0 withInt:[actiontokens size] - 1];
        ELSEaction = OrgMinimaKissvmStatementsStatementParser_parseTokensWithJavaUtilList_(actiontokens);
        [ifsx addConditionWithOrgMinimaKissvmExpressionsExpression:ELSEcondition withOrgMinimaKissvmStatementsStatementBlock:ELSEaction];
      }
      [stats addWithId:ifsx];
    }
    else if ([token java_equalsIgnoreCase:@"WHILE"]) {
      id<JavaUtilList> conditiontokens = OrgMinimaKissvmStatementsStatementParser_getTokensToNextCommandWithJavaUtilList_withInt_(zTokens, currentPosition);
      id<OrgMinimaKissvmExpressionsExpression> WHILEcondition = OrgMinimaKissvmExpressionsExpressionParser_getExpressionWithJavaUtilList_(conditiontokens);
      currentPosition += [((id<JavaUtilList>) nil_chk(conditiontokens)) size] + 1;
      id<JavaUtilList> actiontokens = OrgMinimaKissvmStatementsStatementParser_getEndWHILEWithJavaUtilList_withInt_(zTokens, currentPosition);
      currentPosition += [((id<JavaUtilList>) nil_chk(actiontokens)) size];
      actiontokens = [actiontokens subListWithInt:0 withInt:[actiontokens size] - 1];
      OrgMinimaKissvmStatementsStatementBlock *WHILEaction = OrgMinimaKissvmStatementsStatementParser_parseTokensWithJavaUtilList_(actiontokens);
      OrgMinimaKissvmStatementsCommandsWHILEstatement *ws = new_OrgMinimaKissvmStatementsCommandsWHILEstatement_initWithOrgMinimaKissvmExpressionsExpression_withOrgMinimaKissvmStatementsStatementBlock_(WHILEcondition, WHILEaction);
      [stats addWithId:ws];
    }
    else if ([token java_equalsIgnoreCase:@"ASSERT"]) {
      id<JavaUtilList> returntokens = OrgMinimaKissvmStatementsStatementParser_getTokensToNextCommandWithJavaUtilList_withInt_(zTokens, currentPosition);
      currentPosition += [((id<JavaUtilList>) nil_chk(returntokens)) size];
      id<OrgMinimaKissvmExpressionsExpression> exp = OrgMinimaKissvmExpressionsExpressionParser_getExpressionWithJavaUtilList_(returntokens);
      [stats addWithId:new_OrgMinimaKissvmStatementsCommandsASSERTstatement_initWithOrgMinimaKissvmExpressionsExpression_(exp)];
    }
    else if ([token java_equalsIgnoreCase:@"RETURN"]) {
      id<JavaUtilList> returntokens = OrgMinimaKissvmStatementsStatementParser_getTokensToNextCommandWithJavaUtilList_withInt_(zTokens, currentPosition);
      currentPosition += [((id<JavaUtilList>) nil_chk(returntokens)) size];
      id<OrgMinimaKissvmExpressionsExpression> exp = OrgMinimaKissvmExpressionsExpressionParser_getExpressionWithJavaUtilList_(returntokens);
      [stats addWithId:new_OrgMinimaKissvmStatementsCommandsRETURNstatement_initWithOrgMinimaKissvmExpressionsExpression_(exp)];
    }
    else {
      @throw new_OrgMinimaKissvmExceptionsMinimaParseException_initWithNSString_(JreStrcat("$$", @"Invalid Token where there should be a Command - ", token));
    }
  }
  return new_OrgMinimaKissvmStatementsStatementBlock_initWithJavaUtilList_(stats);
}

id<JavaUtilList> OrgMinimaKissvmStatementsStatementParser_getElseOrElseIfOrEndIFWithJavaUtilList_withInt_withBoolean_(id<JavaUtilList> zTokens, jint zCurrentPosition, jboolean zElseAlso) {
  OrgMinimaKissvmStatementsStatementParser_initialize();
  id<JavaUtilList> rettokens = new_JavaUtilArrayList_init();
  jint currentpos = zCurrentPosition;
  jint total = [((id<JavaUtilList>) nil_chk(zTokens)) size];
  while (currentpos < total) {
    OrgMinimaKissvmTokensToken *tok = [zTokens getWithInt:currentpos];
    if ([((OrgMinimaKissvmTokensToken *) nil_chk(tok)) getTokenType] == OrgMinimaKissvmTokensToken_TOKEN_COMMAND && [((NSString *) nil_chk([tok getToken])) isEqual:@"ENDIF"]) {
      [rettokens addWithId:tok];
      return rettokens;
    }
    else if (zElseAlso && ([tok getTokenType] == OrgMinimaKissvmTokensToken_TOKEN_COMMAND && [((NSString *) nil_chk([tok getToken])) isEqual:@"ELSEIF"])) {
      [rettokens addWithId:tok];
      return rettokens;
    }
    else if (zElseAlso && ([tok getTokenType] == OrgMinimaKissvmTokensToken_TOKEN_COMMAND && [((NSString *) nil_chk([tok getToken])) isEqual:@"ELSE"])) {
      [rettokens addWithId:tok];
      return rettokens;
    }
    else if ([tok getTokenType] == OrgMinimaKissvmTokensToken_TOKEN_COMMAND && [((NSString *) nil_chk([tok getToken])) isEqual:@"IF"]) {
      [rettokens addWithId:tok];
      currentpos++;
      id<JavaUtilList> toks = OrgMinimaKissvmStatementsStatementParser_getElseOrElseIfOrEndIFWithJavaUtilList_withInt_withBoolean_(zTokens, currentpos, false);
      [rettokens addAllWithJavaUtilCollection:toks];
      currentpos += [((id<JavaUtilList>) nil_chk(toks)) size];
    }
    else {
      [rettokens addWithId:tok];
      currentpos++;
    }
  }
  return rettokens;
}

id<JavaUtilList> OrgMinimaKissvmStatementsStatementParser_getEndWHILEWithJavaUtilList_withInt_(id<JavaUtilList> zTokens, jint zCurrentPosition) {
  OrgMinimaKissvmStatementsStatementParser_initialize();
  id<JavaUtilList> rettokens = new_JavaUtilArrayList_init();
  jint currentpos = zCurrentPosition;
  jint total = [((id<JavaUtilList>) nil_chk(zTokens)) size];
  while (currentpos < total) {
    OrgMinimaKissvmTokensToken *tok = [zTokens getWithInt:currentpos];
    if ([((OrgMinimaKissvmTokensToken *) nil_chk(tok)) getTokenType] == OrgMinimaKissvmTokensToken_TOKEN_COMMAND && [((NSString *) nil_chk([tok getToken])) isEqual:@"ENDWHILE"]) {
      [rettokens addWithId:tok];
      return rettokens;
    }
    else if ([tok getTokenType] == OrgMinimaKissvmTokensToken_TOKEN_COMMAND && [((NSString *) nil_chk([tok getToken])) isEqual:@"WHILE"]) {
      [rettokens addWithId:tok];
      currentpos++;
      id<JavaUtilList> toks = OrgMinimaKissvmStatementsStatementParser_getEndWHILEWithJavaUtilList_withInt_(zTokens, currentpos);
      [rettokens addAllWithJavaUtilCollection:toks];
      currentpos += [((id<JavaUtilList>) nil_chk(toks)) size];
    }
    else {
      [rettokens addWithId:tok];
      currentpos++;
    }
  }
  return rettokens;
}

id<JavaUtilList> OrgMinimaKissvmStatementsStatementParser_getTokensToNextCommandWithJavaUtilList_withInt_(id<JavaUtilList> zTokens, jint zCurrentPosition) {
  OrgMinimaKissvmStatementsStatementParser_initialize();
  id<JavaUtilList> rettokens = new_JavaUtilArrayList_init();
  jint ret = zCurrentPosition;
  jint total = [((id<JavaUtilList>) nil_chk(zTokens)) size];
  while (ret < total) {
    OrgMinimaKissvmTokensToken *tok = [zTokens getWithInt:ret];
    if ([((OrgMinimaKissvmTokensToken *) nil_chk(tok)) getTokenType] == OrgMinimaKissvmTokensToken_TOKEN_COMMAND) {
      return rettokens;
    }
    else {
      [rettokens addWithId:tok];
    }
    ret++;
  }
  return rettokens;
}

id<JavaUtilList> OrgMinimaKissvmStatementsStatementParser_getTokensToNextEqualsWithJavaUtilList_withInt_(id<JavaUtilList> zTokens, jint zCurrentPosition) {
  OrgMinimaKissvmStatementsStatementParser_initialize();
  id<JavaUtilList> rettokens = new_JavaUtilArrayList_init();
  jint ret = zCurrentPosition;
  jint total = [((id<JavaUtilList>) nil_chk(zTokens)) size];
  while (ret < total) {
    OrgMinimaKissvmTokensToken *tok = [zTokens getWithInt:ret];
    if ([((OrgMinimaKissvmTokensToken *) nil_chk(tok)) getTokenType] == OrgMinimaKissvmTokensToken_TOKEN_OPERATOR && [((NSString *) nil_chk([tok getToken])) isEqual:@"="]) {
      return rettokens;
    }
    else {
      [rettokens addWithId:tok];
    }
    ret++;
  }
  return rettokens;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgMinimaKissvmStatementsStatementParser)
