//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/utils/json/parser/Yylex.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaUtilsJsonParserYylex")
#ifdef RESTRICT_OrgMinimaUtilsJsonParserYylex
#define INCLUDE_ALL_OrgMinimaUtilsJsonParserYylex 0
#else
#define INCLUDE_ALL_OrgMinimaUtilsJsonParserYylex 1
#endif
#undef RESTRICT_OrgMinimaUtilsJsonParserYylex

#if !defined (OrgMinimaUtilsJsonParserYylex_) && (INCLUDE_ALL_OrgMinimaUtilsJsonParserYylex || defined(INCLUDE_OrgMinimaUtilsJsonParserYylex))
#define OrgMinimaUtilsJsonParserYylex_

@class JavaIoInputStream;
@class JavaIoReader;
@class OrgMinimaUtilsJsonParserYytoken;

@interface OrgMinimaUtilsJsonParserYylex : NSObject

#pragma mark Public

- (void)yybeginWithInt:(jint)newState;

- (jchar)yycharatWithInt:(jint)pos;

- (void)yyclose;

- (jint)yylength;

- (OrgMinimaUtilsJsonParserYytoken *)yylex;

- (void)yypushbackWithInt:(jint)number;

- (void)yyresetWithJavaIoReader:(JavaIoReader *)reader;

- (jint)yystate;

- (NSString *)yytext;

#pragma mark Package-Private

- (instancetype)initWithJavaIoInputStream:(JavaIoInputStream *)inArg;

- (instancetype)initWithJavaIoReader:(JavaIoReader *)inArg;

- (jint)getPosition;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(OrgMinimaUtilsJsonParserYylex)

inline jint OrgMinimaUtilsJsonParserYylex_get_YYEOF(void);
#define OrgMinimaUtilsJsonParserYylex_YYEOF -1
J2OBJC_STATIC_FIELD_CONSTANT(OrgMinimaUtilsJsonParserYylex, YYEOF, jint)

inline jint OrgMinimaUtilsJsonParserYylex_get_YYINITIAL(void);
#define OrgMinimaUtilsJsonParserYylex_YYINITIAL 0
J2OBJC_STATIC_FIELD_CONSTANT(OrgMinimaUtilsJsonParserYylex, YYINITIAL, jint)

inline jint OrgMinimaUtilsJsonParserYylex_get_STRING_BEGIN(void);
#define OrgMinimaUtilsJsonParserYylex_STRING_BEGIN 2
J2OBJC_STATIC_FIELD_CONSTANT(OrgMinimaUtilsJsonParserYylex, STRING_BEGIN, jint)

FOUNDATION_EXPORT void OrgMinimaUtilsJsonParserYylex_initWithJavaIoReader_(OrgMinimaUtilsJsonParserYylex *self, JavaIoReader *inArg);

FOUNDATION_EXPORT OrgMinimaUtilsJsonParserYylex *new_OrgMinimaUtilsJsonParserYylex_initWithJavaIoReader_(JavaIoReader *inArg) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaUtilsJsonParserYylex *create_OrgMinimaUtilsJsonParserYylex_initWithJavaIoReader_(JavaIoReader *inArg);

FOUNDATION_EXPORT void OrgMinimaUtilsJsonParserYylex_initWithJavaIoInputStream_(OrgMinimaUtilsJsonParserYylex *self, JavaIoInputStream *inArg);

FOUNDATION_EXPORT OrgMinimaUtilsJsonParserYylex *new_OrgMinimaUtilsJsonParserYylex_initWithJavaIoInputStream_(JavaIoInputStream *inArg) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaUtilsJsonParserYylex *create_OrgMinimaUtilsJsonParserYylex_initWithJavaIoInputStream_(JavaIoInputStream *inArg);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaUtilsJsonParserYylex)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaUtilsJsonParserYylex")
