//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/system/SystemHandler.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaSystemSystemHandler")
#ifdef RESTRICT_OrgMinimaSystemSystemHandler
#define INCLUDE_ALL_OrgMinimaSystemSystemHandler 0
#else
#define INCLUDE_ALL_OrgMinimaSystemSystemHandler 1
#endif
#undef RESTRICT_OrgMinimaSystemSystemHandler

#if !defined (OrgMinimaSystemSystemHandler_) && (INCLUDE_ALL_OrgMinimaSystemSystemHandler || defined(INCLUDE_OrgMinimaSystemSystemHandler))
#define OrgMinimaSystemSystemHandler_

#define RESTRICT_OrgMinimaUtilsMessagesMessageProcessor 1
#define INCLUDE_OrgMinimaUtilsMessagesMessageProcessor 1
#include "org/minima/utils/messages/MessageProcessor.h"

@class OrgMinimaSystemMain;

@interface OrgMinimaSystemSystemHandler : OrgMinimaUtilsMessagesMessageProcessor

#pragma mark Public

- (instancetype)initWithOrgMinimaSystemMain:(OrgMinimaSystemMain *)zMain;

- (instancetype)initWithOrgMinimaSystemMain:(OrgMinimaSystemMain *)zMain
                               withNSString:(NSString *)zName;

- (OrgMinimaSystemMain *)getMainHandler;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaSystemSystemHandler)

FOUNDATION_EXPORT void OrgMinimaSystemSystemHandler_initWithOrgMinimaSystemMain_(OrgMinimaSystemSystemHandler *self, OrgMinimaSystemMain *zMain);

FOUNDATION_EXPORT void OrgMinimaSystemSystemHandler_initWithOrgMinimaSystemMain_withNSString_(OrgMinimaSystemSystemHandler *self, OrgMinimaSystemMain *zMain, NSString *zName);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaSystemSystemHandler)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaSystemSystemHandler")
