//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/system/input/functions/transfer/exportcoin.java
//

#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "org/minima/objects/base/MiniData.h"
#include "org/minima/system/Main.h"
#include "org/minima/system/brains/ConsensusHandler.h"
#include "org/minima/system/brains/ConsensusUser.h"
#include "org/minima/system/input/CommandFunction.h"
#include "org/minima/system/input/functions/transfer/exportcoin.h"
#include "org/minima/utils/messages/Message.h"

@implementation OrgMinimaSystemInputFunctionsTransferexportcoin

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgMinimaSystemInputFunctionsTransferexportcoin_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (void)doFunctionWithNSStringArray:(IOSObjectArray *)zInput {
  NSString *pubks = IOSObjectArray_Get(nil_chk(zInput), 1);
  OrgMinimaUtilsMessagesMessage *export_ = [((OrgMinimaUtilsMessagesMessage *) nil_chk([self getResponseMessageWithNSString:OrgMinimaSystemBrainsConsensusUser_CONSENSUS_EXPORTCOIN])) addObjectWithNSString:@"coinid" withId:create_OrgMinimaObjectsBaseMiniData_initWithNSString_(pubks)];
  [((OrgMinimaSystemBrainsConsensusHandler *) nil_chk([((OrgMinimaSystemMain *) nil_chk([self getMainHandler])) getConsensusHandler])) PostMessageWithOrgMinimaUtilsMessagesMessage:export_];
}

- (OrgMinimaSystemInputCommandFunction *)getNewFunction {
  return create_OrgMinimaSystemInputFunctionsTransferexportcoin_init();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, 2, -1, -1, -1 },
    { NULL, "LOrgMinimaSystemInputCommandFunction;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(doFunctionWithNSStringArray:);
  methods[2].selector = @selector(getNewFunction);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "doFunction", "[LNSString;", "LJavaLangException;" };
  static const J2ObjcClassInfo _OrgMinimaSystemInputFunctionsTransferexportcoin = { "exportcoin", "org.minima.system.input.functions.transfer", ptrTable, methods, NULL, 7, 0x1, 3, 0, -1, -1, -1, -1, -1 };
  return &_OrgMinimaSystemInputFunctionsTransferexportcoin;
}

@end

void OrgMinimaSystemInputFunctionsTransferexportcoin_init(OrgMinimaSystemInputFunctionsTransferexportcoin *self) {
  OrgMinimaSystemInputCommandFunction_initWithNSString_(self, @"exportcoin");
  [self setHelpWithNSString:@"[coinid]" withNSString:@"export the proof of a single coin. Share it." withNSString:@"Never worry about losing your coin proofs. Share the details with friends, they can't spend the coins, and retrieve them when you need them."];
}

OrgMinimaSystemInputFunctionsTransferexportcoin *new_OrgMinimaSystemInputFunctionsTransferexportcoin_init() {
  J2OBJC_NEW_IMPL(OrgMinimaSystemInputFunctionsTransferexportcoin, init)
}

OrgMinimaSystemInputFunctionsTransferexportcoin *create_OrgMinimaSystemInputFunctionsTransferexportcoin_init() {
  J2OBJC_CREATE_IMPL(OrgMinimaSystemInputFunctionsTransferexportcoin, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgMinimaSystemInputFunctionsTransferexportcoin)

J2OBJC_NAME_MAPPING(OrgMinimaSystemInputFunctionsTransferexportcoin, "org.minima.system.input.functions.transfer", "OrgMinimaSystemInputFunctionsTransfer")
