//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/system/input/functions/transfer/importkey.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaSystemInputFunctionsTransferImportkey")
#ifdef RESTRICT_OrgMinimaSystemInputFunctionsTransferImportkey
#define INCLUDE_ALL_OrgMinimaSystemInputFunctionsTransferImportkey 0
#else
#define INCLUDE_ALL_OrgMinimaSystemInputFunctionsTransferImportkey 1
#endif
#undef RESTRICT_OrgMinimaSystemInputFunctionsTransferImportkey

#if !defined (OrgMinimaSystemInputFunctionsTransferimportkey_) && (INCLUDE_ALL_OrgMinimaSystemInputFunctionsTransferImportkey || defined(INCLUDE_OrgMinimaSystemInputFunctionsTransferimportkey))
#define OrgMinimaSystemInputFunctionsTransferimportkey_

#define RESTRICT_OrgMinimaSystemInputCommandFunction 1
#define INCLUDE_OrgMinimaSystemInputCommandFunction 1
#include "org/minima/system/input/CommandFunction.h"

@class IOSObjectArray;

@interface OrgMinimaSystemInputFunctionsTransferimportkey : OrgMinimaSystemInputCommandFunction

#pragma mark Public

- (instancetype)init;

- (void)doFunctionWithNSStringArray:(IOSObjectArray *)zInput;

- (OrgMinimaSystemInputCommandFunction *)getNewFunction;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaSystemInputFunctionsTransferimportkey)

FOUNDATION_EXPORT void OrgMinimaSystemInputFunctionsTransferimportkey_init(OrgMinimaSystemInputFunctionsTransferimportkey *self);

FOUNDATION_EXPORT OrgMinimaSystemInputFunctionsTransferimportkey *new_OrgMinimaSystemInputFunctionsTransferimportkey_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaSystemInputFunctionsTransferimportkey *create_OrgMinimaSystemInputFunctionsTransferimportkey_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaSystemInputFunctionsTransferimportkey)

@compatibility_alias OrgMinimaSystemInputFunctionsTransferImportkey OrgMinimaSystemInputFunctionsTransferimportkey;

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaSystemInputFunctionsTransferImportkey")
