//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/kissvm/values/NumberValue.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaKissvmValuesNumberValue")
#ifdef RESTRICT_OrgMinimaKissvmValuesNumberValue
#define INCLUDE_ALL_OrgMinimaKissvmValuesNumberValue 0
#else
#define INCLUDE_ALL_OrgMinimaKissvmValuesNumberValue 1
#endif
#undef RESTRICT_OrgMinimaKissvmValuesNumberValue

#if !defined (OrgMinimaKissvmValuesNumberValue_) && (INCLUDE_ALL_OrgMinimaKissvmValuesNumberValue || defined(INCLUDE_OrgMinimaKissvmValuesNumberValue))
#define OrgMinimaKissvmValuesNumberValue_

#define RESTRICT_OrgMinimaKissvmValuesValue 1
#define INCLUDE_OrgMinimaKissvmValuesValue 1
#include "org/minima/kissvm/values/Value.h"

@class OrgMinimaObjectsBaseMiniNumber;

@interface OrgMinimaKissvmValuesNumberValue : OrgMinimaKissvmValuesValue

#pragma mark Public

- (instancetype)initWithDouble:(jdouble)zValue;

- (instancetype)initWithInt:(jint)zValue;

- (instancetype)initWithLong:(jlong)zValue;

- (instancetype)initWithOrgMinimaObjectsBaseMiniNumber:(OrgMinimaObjectsBaseMiniNumber *)zValue;

- (instancetype)initWithNSString:(NSString *)zNumber;

- (OrgMinimaKissvmValuesValue *)addWithOrgMinimaKissvmValuesValue:(OrgMinimaKissvmValuesValue *)zValue;

- (OrgMinimaKissvmValuesValue *)divWithOrgMinimaKissvmValuesValue:(OrgMinimaKissvmValuesValue *)zValue;

- (jint)getValueType;

- (jboolean)isEqualWithOrgMinimaKissvmValuesValue:(OrgMinimaKissvmValuesValue *)zValue;

- (jboolean)isLessWithOrgMinimaKissvmValuesValue:(OrgMinimaKissvmValuesValue *)zValue;

- (jboolean)isLessEqualWithOrgMinimaKissvmValuesValue:(OrgMinimaKissvmValuesValue *)zValue;

- (jboolean)isMoreWithOrgMinimaKissvmValuesValue:(OrgMinimaKissvmValuesValue *)zValue;

- (jboolean)isMoreEqualWithOrgMinimaKissvmValuesValue:(OrgMinimaKissvmValuesValue *)zValue;

- (OrgMinimaKissvmValuesValue *)multWithOrgMinimaKissvmValuesValue:(OrgMinimaKissvmValuesValue *)zValue;

- (OrgMinimaKissvmValuesValue *)subWithOrgMinimaKissvmValuesValue:(OrgMinimaKissvmValuesValue *)zValue;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaKissvmValuesNumberValue)

inline jint OrgMinimaKissvmValuesNumberValue_get_VALUE_NUMBER(void);
#define OrgMinimaKissvmValuesNumberValue_VALUE_NUMBER 2
J2OBJC_STATIC_FIELD_CONSTANT(OrgMinimaKissvmValuesNumberValue, VALUE_NUMBER, jint)

FOUNDATION_EXPORT void OrgMinimaKissvmValuesNumberValue_initWithInt_(OrgMinimaKissvmValuesNumberValue *self, jint zValue);

FOUNDATION_EXPORT OrgMinimaKissvmValuesNumberValue *new_OrgMinimaKissvmValuesNumberValue_initWithInt_(jint zValue) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaKissvmValuesNumberValue *create_OrgMinimaKissvmValuesNumberValue_initWithInt_(jint zValue);

FOUNDATION_EXPORT void OrgMinimaKissvmValuesNumberValue_initWithLong_(OrgMinimaKissvmValuesNumberValue *self, jlong zValue);

FOUNDATION_EXPORT OrgMinimaKissvmValuesNumberValue *new_OrgMinimaKissvmValuesNumberValue_initWithLong_(jlong zValue) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaKissvmValuesNumberValue *create_OrgMinimaKissvmValuesNumberValue_initWithLong_(jlong zValue);

FOUNDATION_EXPORT void OrgMinimaKissvmValuesNumberValue_initWithDouble_(OrgMinimaKissvmValuesNumberValue *self, jdouble zValue);

FOUNDATION_EXPORT OrgMinimaKissvmValuesNumberValue *new_OrgMinimaKissvmValuesNumberValue_initWithDouble_(jdouble zValue) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaKissvmValuesNumberValue *create_OrgMinimaKissvmValuesNumberValue_initWithDouble_(jdouble zValue);

FOUNDATION_EXPORT void OrgMinimaKissvmValuesNumberValue_initWithOrgMinimaObjectsBaseMiniNumber_(OrgMinimaKissvmValuesNumberValue *self, OrgMinimaObjectsBaseMiniNumber *zValue);

FOUNDATION_EXPORT OrgMinimaKissvmValuesNumberValue *new_OrgMinimaKissvmValuesNumberValue_initWithOrgMinimaObjectsBaseMiniNumber_(OrgMinimaObjectsBaseMiniNumber *zValue) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaKissvmValuesNumberValue *create_OrgMinimaKissvmValuesNumberValue_initWithOrgMinimaObjectsBaseMiniNumber_(OrgMinimaObjectsBaseMiniNumber *zValue);

FOUNDATION_EXPORT void OrgMinimaKissvmValuesNumberValue_initWithNSString_(OrgMinimaKissvmValuesNumberValue *self, NSString *zNumber);

FOUNDATION_EXPORT OrgMinimaKissvmValuesNumberValue *new_OrgMinimaKissvmValuesNumberValue_initWithNSString_(NSString *zNumber) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaKissvmValuesNumberValue *create_OrgMinimaKissvmValuesNumberValue_initWithNSString_(NSString *zNumber);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaKissvmValuesNumberValue)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaKissvmValuesNumberValue")
