//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/system/input/functions/txns/txnexport.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaSystemInputFunctionsTxnsTxnexport")
#ifdef RESTRICT_OrgMinimaSystemInputFunctionsTxnsTxnexport
#define INCLUDE_ALL_OrgMinimaSystemInputFunctionsTxnsTxnexport 0
#else
#define INCLUDE_ALL_OrgMinimaSystemInputFunctionsTxnsTxnexport 1
#endif
#undef RESTRICT_OrgMinimaSystemInputFunctionsTxnsTxnexport

#if !defined (OrgMinimaSystemInputFunctionsTxnstxnexport_) && (INCLUDE_ALL_OrgMinimaSystemInputFunctionsTxnsTxnexport || defined(INCLUDE_OrgMinimaSystemInputFunctionsTxnstxnexport))
#define OrgMinimaSystemInputFunctionsTxnstxnexport_

@interface OrgMinimaSystemInputFunctionsTxnstxnexport : NSObject

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaSystemInputFunctionsTxnstxnexport)

FOUNDATION_EXPORT void OrgMinimaSystemInputFunctionsTxnstxnexport_init(OrgMinimaSystemInputFunctionsTxnstxnexport *self);

FOUNDATION_EXPORT OrgMinimaSystemInputFunctionsTxnstxnexport *new_OrgMinimaSystemInputFunctionsTxnstxnexport_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaSystemInputFunctionsTxnstxnexport *create_OrgMinimaSystemInputFunctionsTxnstxnexport_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaSystemInputFunctionsTxnstxnexport)

@compatibility_alias OrgMinimaSystemInputFunctionsTxnsTxnexport OrgMinimaSystemInputFunctionsTxnstxnexport;

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaSystemInputFunctionsTxnsTxnexport")
