//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/system/input/functions/txns/txnremoutput.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaSystemInputFunctionsTxnsTxnremoutput")
#ifdef RESTRICT_OrgMinimaSystemInputFunctionsTxnsTxnremoutput
#define INCLUDE_ALL_OrgMinimaSystemInputFunctionsTxnsTxnremoutput 0
#else
#define INCLUDE_ALL_OrgMinimaSystemInputFunctionsTxnsTxnremoutput 1
#endif
#undef RESTRICT_OrgMinimaSystemInputFunctionsTxnsTxnremoutput

#if !defined (OrgMinimaSystemInputFunctionsTxnstxnremoutput_) && (INCLUDE_ALL_OrgMinimaSystemInputFunctionsTxnsTxnremoutput || defined(INCLUDE_OrgMinimaSystemInputFunctionsTxnstxnremoutput))
#define OrgMinimaSystemInputFunctionsTxnstxnremoutput_

#define RESTRICT_OrgMinimaSystemInputCommandFunction 1
#define INCLUDE_OrgMinimaSystemInputCommandFunction 1
#include "org/minima/system/input/CommandFunction.h"

@class IOSObjectArray;

@interface OrgMinimaSystemInputFunctionsTxnstxnremoutput : OrgMinimaSystemInputCommandFunction

#pragma mark Public

- (instancetype)init;

- (void)doFunctionWithNSStringArray:(IOSObjectArray *)zInput;

- (OrgMinimaSystemInputCommandFunction *)getNewFunction;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaSystemInputFunctionsTxnstxnremoutput)

FOUNDATION_EXPORT void OrgMinimaSystemInputFunctionsTxnstxnremoutput_init(OrgMinimaSystemInputFunctionsTxnstxnremoutput *self);

FOUNDATION_EXPORT OrgMinimaSystemInputFunctionsTxnstxnremoutput *new_OrgMinimaSystemInputFunctionsTxnstxnremoutput_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaSystemInputFunctionsTxnstxnremoutput *create_OrgMinimaSystemInputFunctionsTxnstxnremoutput_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaSystemInputFunctionsTxnstxnremoutput)

@compatibility_alias OrgMinimaSystemInputFunctionsTxnsTxnremoutput OrgMinimaSystemInputFunctionsTxnstxnremoutput;

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaSystemInputFunctionsTxnsTxnremoutput")
