//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/database/userdb/java/reltxpow.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaDatabaseUserdbJavaReltxpow")
#ifdef RESTRICT_OrgMinimaDatabaseUserdbJavaReltxpow
#define INCLUDE_ALL_OrgMinimaDatabaseUserdbJavaReltxpow 0
#else
#define INCLUDE_ALL_OrgMinimaDatabaseUserdbJavaReltxpow 1
#endif
#undef RESTRICT_OrgMinimaDatabaseUserdbJavaReltxpow

#if !defined (OrgMinimaDatabaseUserdbJavareltxpow_) && (INCLUDE_ALL_OrgMinimaDatabaseUserdbJavaReltxpow || defined(INCLUDE_OrgMinimaDatabaseUserdbJavareltxpow))
#define OrgMinimaDatabaseUserdbJavareltxpow_

#define RESTRICT_OrgMinimaUtilsStreamable 1
#define INCLUDE_OrgMinimaUtilsStreamable 1
#include "org/minima/utils/Streamable.h"

@class JavaIoDataInputStream;
@class JavaIoDataOutputStream;
@class OrgMinimaObjectsBaseMiniNumber;
@class OrgMinimaObjectsTxPOW;
@class OrgMinimaUtilsJsonJSONObject;

@interface OrgMinimaDatabaseUserdbJavareltxpow : NSObject < OrgMinimaUtilsStreamable > {
 @public
  OrgMinimaObjectsTxPOW *mTxPow_;
  OrgMinimaObjectsBaseMiniNumber *mValue_;
}

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithOrgMinimaObjectsTxPOW:(OrgMinimaObjectsTxPOW *)zTxPow
           withOrgMinimaObjectsBaseMiniNumber:(OrgMinimaObjectsBaseMiniNumber *)zValue;

- (OrgMinimaObjectsBaseMiniNumber *)getChange;

- (OrgMinimaObjectsTxPOW *)getTxPow;

- (void)readDataStreamWithJavaIoDataInputStream:(JavaIoDataInputStream *)zIn;

- (OrgMinimaUtilsJsonJSONObject *)toJSON;

- (void)writeDataStreamWithJavaIoDataOutputStream:(JavaIoDataOutputStream *)zOut;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaDatabaseUserdbJavareltxpow)

J2OBJC_FIELD_SETTER(OrgMinimaDatabaseUserdbJavareltxpow, mTxPow_, OrgMinimaObjectsTxPOW *)
J2OBJC_FIELD_SETTER(OrgMinimaDatabaseUserdbJavareltxpow, mValue_, OrgMinimaObjectsBaseMiniNumber *)

FOUNDATION_EXPORT void OrgMinimaDatabaseUserdbJavareltxpow_init(OrgMinimaDatabaseUserdbJavareltxpow *self);

FOUNDATION_EXPORT OrgMinimaDatabaseUserdbJavareltxpow *new_OrgMinimaDatabaseUserdbJavareltxpow_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaDatabaseUserdbJavareltxpow *create_OrgMinimaDatabaseUserdbJavareltxpow_init(void);

FOUNDATION_EXPORT void OrgMinimaDatabaseUserdbJavareltxpow_initWithOrgMinimaObjectsTxPOW_withOrgMinimaObjectsBaseMiniNumber_(OrgMinimaDatabaseUserdbJavareltxpow *self, OrgMinimaObjectsTxPOW *zTxPow, OrgMinimaObjectsBaseMiniNumber *zValue);

FOUNDATION_EXPORT OrgMinimaDatabaseUserdbJavareltxpow *new_OrgMinimaDatabaseUserdbJavareltxpow_initWithOrgMinimaObjectsTxPOW_withOrgMinimaObjectsBaseMiniNumber_(OrgMinimaObjectsTxPOW *zTxPow, OrgMinimaObjectsBaseMiniNumber *zValue) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaDatabaseUserdbJavareltxpow *create_OrgMinimaDatabaseUserdbJavareltxpow_initWithOrgMinimaObjectsTxPOW_withOrgMinimaObjectsBaseMiniNumber_(OrgMinimaObjectsTxPOW *zTxPow, OrgMinimaObjectsBaseMiniNumber *zValue);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaDatabaseUserdbJavareltxpow)

@compatibility_alias OrgMinimaDatabaseUserdbJavaReltxpow OrgMinimaDatabaseUserdbJavareltxpow;

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaDatabaseUserdbJavaReltxpow")
