//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/miniscript/expressions/ConstantExpression.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaMiniscriptExpressionsConstantExpression")
#ifdef RESTRICT_OrgMinimaMiniscriptExpressionsConstantExpression
#define INCLUDE_ALL_OrgMinimaMiniscriptExpressionsConstantExpression 0
#else
#define INCLUDE_ALL_OrgMinimaMiniscriptExpressionsConstantExpression 1
#endif
#undef RESTRICT_OrgMinimaMiniscriptExpressionsConstantExpression

#if !defined (OrgMinimaMiniscriptExpressionsConstantExpression_) && (INCLUDE_ALL_OrgMinimaMiniscriptExpressionsConstantExpression || defined(INCLUDE_OrgMinimaMiniscriptExpressionsConstantExpression))
#define OrgMinimaMiniscriptExpressionsConstantExpression_

#define RESTRICT_OrgMinimaMiniscriptExpressionsExpression 1
#define INCLUDE_OrgMinimaMiniscriptExpressionsExpression 1
#include "org/minima/miniscript/expressions/Expression.h"

@class OrgMinimaMiniscriptContract;
@class OrgMinimaMiniscriptValuesValue;

@interface OrgMinimaMiniscriptExpressionsConstantExpression : NSObject < OrgMinimaMiniscriptExpressionsExpression >

#pragma mark Public

- (instancetype)initWithOrgMinimaMiniscriptValuesValue:(OrgMinimaMiniscriptValuesValue *)zValue;

- (OrgMinimaMiniscriptValuesValue *)getValueWithOrgMinimaMiniscriptContract:(OrgMinimaMiniscriptContract *)zContract;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaMiniscriptExpressionsConstantExpression)

FOUNDATION_EXPORT void OrgMinimaMiniscriptExpressionsConstantExpression_initWithOrgMinimaMiniscriptValuesValue_(OrgMinimaMiniscriptExpressionsConstantExpression *self, OrgMinimaMiniscriptValuesValue *zValue);

FOUNDATION_EXPORT OrgMinimaMiniscriptExpressionsConstantExpression *new_OrgMinimaMiniscriptExpressionsConstantExpression_initWithOrgMinimaMiniscriptValuesValue_(OrgMinimaMiniscriptValuesValue *zValue) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaMiniscriptExpressionsConstantExpression *create_OrgMinimaMiniscriptExpressionsConstantExpression_initWithOrgMinimaMiniscriptValuesValue_(OrgMinimaMiniscriptValuesValue *zValue);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaMiniscriptExpressionsConstantExpression)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaMiniscriptExpressionsConstantExpression")
