//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/utils/bretty/maintree.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaUtilsBrettyMaintree")
#ifdef RESTRICT_OrgMinimaUtilsBrettyMaintree
#define INCLUDE_ALL_OrgMinimaUtilsBrettyMaintree 0
#else
#define INCLUDE_ALL_OrgMinimaUtilsBrettyMaintree 1
#endif
#undef RESTRICT_OrgMinimaUtilsBrettyMaintree

#if !defined (OrgMinimaUtilsBrettymaintree_) && (INCLUDE_ALL_OrgMinimaUtilsBrettyMaintree || defined(INCLUDE_OrgMinimaUtilsBrettymaintree))
#define OrgMinimaUtilsBrettymaintree_

@class IOSObjectArray;

@interface OrgMinimaUtilsBrettymaintree : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)mainWithNSStringArray:(IOSObjectArray *)zArgs;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaUtilsBrettymaintree)

FOUNDATION_EXPORT void OrgMinimaUtilsBrettymaintree_init(OrgMinimaUtilsBrettymaintree *self);

FOUNDATION_EXPORT OrgMinimaUtilsBrettymaintree *new_OrgMinimaUtilsBrettymaintree_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaUtilsBrettymaintree *create_OrgMinimaUtilsBrettymaintree_init(void);

FOUNDATION_EXPORT void OrgMinimaUtilsBrettymaintree_mainWithNSStringArray_(IOSObjectArray *zArgs);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaUtilsBrettymaintree)

@compatibility_alias OrgMinimaUtilsBrettyMaintree OrgMinimaUtilsBrettymaintree;

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaUtilsBrettyMaintree")
