//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/utils/bretty/StandardTreeNodeConverters.java
//

#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/io/File.h"
#include "java/util/ArrayList.h"
#include "java/util/Arrays.h"
#include "java/util/List.h"
#include "org/minima/utils/bretty/StandardTreeNodeConverters.h"
#include "org/minima/utils/bretty/TreeNodeConverter.h"

@interface OrgMinimaUtilsBrettyStandardTreeNodeConverters_1 : NSObject < OrgMinimaUtilsBrettyTreeNodeConverter >

- (instancetype)init;

- (NSString *)nameWithId:(JavaIoFile *)file;

- (id<JavaUtilList>)childrenWithId:(JavaIoFile *)file;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaUtilsBrettyStandardTreeNodeConverters_1)

__attribute__((unused)) static void OrgMinimaUtilsBrettyStandardTreeNodeConverters_1_init(OrgMinimaUtilsBrettyStandardTreeNodeConverters_1 *self);

__attribute__((unused)) static OrgMinimaUtilsBrettyStandardTreeNodeConverters_1 *new_OrgMinimaUtilsBrettyStandardTreeNodeConverters_1_init(void) NS_RETURNS_RETAINED;

__attribute__((unused)) static OrgMinimaUtilsBrettyStandardTreeNodeConverters_1 *create_OrgMinimaUtilsBrettyStandardTreeNodeConverters_1_init(void);

J2OBJC_INITIALIZED_DEFN(OrgMinimaUtilsBrettyStandardTreeNodeConverters)

id<OrgMinimaUtilsBrettyTreeNodeConverter> OrgMinimaUtilsBrettyStandardTreeNodeConverters_FILE;

@implementation OrgMinimaUtilsBrettyStandardTreeNodeConverters

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgMinimaUtilsBrettyStandardTreeNodeConverters_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "FILE", "LOrgMinimaUtilsBrettyTreeNodeConverter;", .constantValue.asLong = 0, 0x19, -1, 0, 1, -1 },
  };
  static const void *ptrTable[] = { &OrgMinimaUtilsBrettyStandardTreeNodeConverters_FILE, "Lorg/minima/utils/bretty/TreeNodeConverter<Ljava/io/File;>;" };
  static const J2ObjcClassInfo _OrgMinimaUtilsBrettyStandardTreeNodeConverters = { "StandardTreeNodeConverters", "org.minima.utils.bretty", ptrTable, methods, fields, 7, 0x1, 1, 1, -1, -1, -1, -1, -1 };
  return &_OrgMinimaUtilsBrettyStandardTreeNodeConverters;
}

+ (void)initialize {
  if (self == [OrgMinimaUtilsBrettyStandardTreeNodeConverters class]) {
    JreStrongAssignAndConsume(&OrgMinimaUtilsBrettyStandardTreeNodeConverters_FILE, new_OrgMinimaUtilsBrettyStandardTreeNodeConverters_1_init());
    J2OBJC_SET_INITIALIZED(OrgMinimaUtilsBrettyStandardTreeNodeConverters)
  }
}

@end

void OrgMinimaUtilsBrettyStandardTreeNodeConverters_init(OrgMinimaUtilsBrettyStandardTreeNodeConverters *self) {
  NSObject_init(self);
}

OrgMinimaUtilsBrettyStandardTreeNodeConverters *new_OrgMinimaUtilsBrettyStandardTreeNodeConverters_init() {
  J2OBJC_NEW_IMPL(OrgMinimaUtilsBrettyStandardTreeNodeConverters, init)
}

OrgMinimaUtilsBrettyStandardTreeNodeConverters *create_OrgMinimaUtilsBrettyStandardTreeNodeConverters_init() {
  J2OBJC_CREATE_IMPL(OrgMinimaUtilsBrettyStandardTreeNodeConverters, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgMinimaUtilsBrettyStandardTreeNodeConverters)

@implementation OrgMinimaUtilsBrettyStandardTreeNodeConverters_1

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  OrgMinimaUtilsBrettyStandardTreeNodeConverters_1_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (NSString *)nameWithId:(JavaIoFile *)file {
  return [((JavaIoFile *) nil_chk(file)) getName];
}

- (id<JavaUtilList>)childrenWithId:(JavaIoFile *)file {
  id<JavaUtilList> files = create_JavaUtilArrayList_init();
  if ([((JavaIoFile *) nil_chk(file)) isDirectory]) {
    [files addAllWithJavaUtilCollection:JavaUtilArrays_asListWithNSObjectArray_([file listFiles])];
  }
  return files;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "LJavaUtilList;", 0x1, 2, 1, -1, 3, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(nameWithId:);
  methods[2].selector = @selector(childrenWithId:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "name", "LJavaIoFile;", "children", "(Ljava/io/File;)Ljava/util/List<+Ljava/io/File;>;", "LOrgMinimaUtilsBrettyStandardTreeNodeConverters;", "Ljava/lang/Object;Lorg/minima/utils/bretty/TreeNodeConverter<Ljava/io/File;>;" };
  static const J2ObjcClassInfo _OrgMinimaUtilsBrettyStandardTreeNodeConverters_1 = { "", "org.minima.utils.bretty", ptrTable, methods, NULL, 7, 0x8018, 3, 0, 4, -1, -1, 5, -1 };
  return &_OrgMinimaUtilsBrettyStandardTreeNodeConverters_1;
}

@end

void OrgMinimaUtilsBrettyStandardTreeNodeConverters_1_init(OrgMinimaUtilsBrettyStandardTreeNodeConverters_1 *self) {
  NSObject_init(self);
}

OrgMinimaUtilsBrettyStandardTreeNodeConverters_1 *new_OrgMinimaUtilsBrettyStandardTreeNodeConverters_1_init() {
  J2OBJC_NEW_IMPL(OrgMinimaUtilsBrettyStandardTreeNodeConverters_1, init)
}

OrgMinimaUtilsBrettyStandardTreeNodeConverters_1 *create_OrgMinimaUtilsBrettyStandardTreeNodeConverters_1_init() {
  J2OBJC_CREATE_IMPL(OrgMinimaUtilsBrettyStandardTreeNodeConverters_1, init)
}
