//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/utils/bretty/TreeNodeConverter.java
//

#include "J2ObjC_source.h"
#include "org/minima/utils/bretty/TreeNodeConverter.h"

@interface OrgMinimaUtilsBrettyTreeNodeConverter : NSObject

@end

@implementation OrgMinimaUtilsBrettyTreeNodeConverter

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSString;", 0x401, 0, 1, -1, 2, -1, -1 },
    { NULL, "LJavaUtilList;", 0x401, 3, 1, -1, 4, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(nameWithId:);
  methods[1].selector = @selector(childrenWithId:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "name", "LNSObject;", "(TT;)Ljava/lang/String;", "children", "(TT;)Ljava/util/List<+TT;>;", "<T:Ljava/lang/Object;>Ljava/lang/Object;" };
  static const J2ObjcClassInfo _OrgMinimaUtilsBrettyTreeNodeConverter = { "TreeNodeConverter", "org.minima.utils.bretty", ptrTable, methods, NULL, 7, 0x609, 2, 0, -1, -1, -1, 5, -1 };
  return &_OrgMinimaUtilsBrettyTreeNodeConverter;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgMinimaUtilsBrettyTreeNodeConverter)
