//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/utils/digest/ExtendedDigest.java
//

#include "J2ObjC_source.h"
#include "org/minima/utils/digest/ExtendedDigest.h"

@interface OrgMinimaUtilsDigestExtendedDigest : NSObject

@end

@implementation OrgMinimaUtilsDigestExtendedDigest

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "I", 0x401, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(getByteLength);
  #pragma clang diagnostic pop
  static const J2ObjcClassInfo _OrgMinimaUtilsDigestExtendedDigest = { "ExtendedDigest", "org.minima.utils.digest", NULL, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, -1, -1 };
  return &_OrgMinimaUtilsDigestExtendedDigest;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgMinimaUtilsDigestExtendedDigest)
