//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/utils/digest/GeneralDigest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaUtilsDigestGeneralDigest")
#ifdef RESTRICT_OrgMinimaUtilsDigestGeneralDigest
#define INCLUDE_ALL_OrgMinimaUtilsDigestGeneralDigest 0
#else
#define INCLUDE_ALL_OrgMinimaUtilsDigestGeneralDigest 1
#endif
#undef RESTRICT_OrgMinimaUtilsDigestGeneralDigest

#if !defined (OrgMinimaUtilsDigestGeneralDigest_) && (INCLUDE_ALL_OrgMinimaUtilsDigestGeneralDigest || defined(INCLUDE_OrgMinimaUtilsDigestGeneralDigest))
#define OrgMinimaUtilsDigestGeneralDigest_

#define RESTRICT_OrgMinimaUtilsDigestExtendedDigest 1
#define INCLUDE_OrgMinimaUtilsDigestExtendedDigest 1
#include "org/minima/utils/digest/ExtendedDigest.h"

#define RESTRICT_OrgMinimaUtilsDigestMemoable 1
#define INCLUDE_OrgMinimaUtilsDigestMemoable 1
#include "org/minima/utils/digest/Memoable.h"

@class IOSByteArray;

@interface OrgMinimaUtilsDigestGeneralDigest : NSObject < OrgMinimaUtilsDigestExtendedDigest, OrgMinimaUtilsDigestMemoable >

#pragma mark Public

- (void)finish;

- (jint)getByteLength;

- (void)reset;

- (void)updateWithByte:(jbyte)inArg;

- (void)updateWithByteArray:(IOSByteArray *)inArg
                    withInt:(jint)inOff
                    withInt:(jint)len;

#pragma mark Protected

- (instancetype)init;

- (instancetype)initWithByteArray:(IOSByteArray *)encodedState;

- (instancetype)initWithOrgMinimaUtilsDigestGeneralDigest:(OrgMinimaUtilsDigestGeneralDigest *)t;

- (void)copyInWithOrgMinimaUtilsDigestGeneralDigest:(OrgMinimaUtilsDigestGeneralDigest *)t OBJC_METHOD_FAMILY_NONE;

- (void)populateStateWithByteArray:(IOSByteArray *)state;

- (void)processBlock;

- (void)processLengthWithLong:(jlong)bitLength;

- (void)processWordWithByteArray:(IOSByteArray *)inArg
                         withInt:(jint)inOff;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaUtilsDigestGeneralDigest)

FOUNDATION_EXPORT void OrgMinimaUtilsDigestGeneralDigest_init(OrgMinimaUtilsDigestGeneralDigest *self);

FOUNDATION_EXPORT void OrgMinimaUtilsDigestGeneralDigest_initWithOrgMinimaUtilsDigestGeneralDigest_(OrgMinimaUtilsDigestGeneralDigest *self, OrgMinimaUtilsDigestGeneralDigest *t);

FOUNDATION_EXPORT void OrgMinimaUtilsDigestGeneralDigest_initWithByteArray_(OrgMinimaUtilsDigestGeneralDigest *self, IOSByteArray *encodedState);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaUtilsDigestGeneralDigest)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaUtilsDigestGeneralDigest")
