//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/kissvm/functions/maths/FLOOR.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaKissvmFunctionsMathsFLOOR")
#ifdef RESTRICT_OrgMinimaKissvmFunctionsMathsFLOOR
#define INCLUDE_ALL_OrgMinimaKissvmFunctionsMathsFLOOR 0
#else
#define INCLUDE_ALL_OrgMinimaKissvmFunctionsMathsFLOOR 1
#endif
#undef RESTRICT_OrgMinimaKissvmFunctionsMathsFLOOR

#if !defined (OrgMinimaKissvmFunctionsMathsFLOOR_) && (INCLUDE_ALL_OrgMinimaKissvmFunctionsMathsFLOOR || defined(INCLUDE_OrgMinimaKissvmFunctionsMathsFLOOR))
#define OrgMinimaKissvmFunctionsMathsFLOOR_

#define RESTRICT_OrgMinimaKissvmFunctionsMinimaFunction 1
#define INCLUDE_OrgMinimaKissvmFunctionsMinimaFunction 1
#include "org/minima/kissvm/functions/MinimaFunction.h"

@class OrgMinimaKissvmContract;
@class OrgMinimaKissvmValuesValue;

@interface OrgMinimaKissvmFunctionsMathsFLOOR : OrgMinimaKissvmFunctionsMinimaFunction

#pragma mark Public

- (instancetype)init;

- (OrgMinimaKissvmFunctionsMinimaFunction *)getNewFunction;

- (OrgMinimaKissvmValuesValue *)runFunctionWithOrgMinimaKissvmContract:(OrgMinimaKissvmContract *)zContract;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMinimaKissvmFunctionsMathsFLOOR)

FOUNDATION_EXPORT void OrgMinimaKissvmFunctionsMathsFLOOR_init(OrgMinimaKissvmFunctionsMathsFLOOR *self);

FOUNDATION_EXPORT OrgMinimaKissvmFunctionsMathsFLOOR *new_OrgMinimaKissvmFunctionsMathsFLOOR_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaKissvmFunctionsMathsFLOOR *create_OrgMinimaKissvmFunctionsMathsFLOOR_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaKissvmFunctionsMathsFLOOR)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaKissvmFunctionsMathsFLOOR")
