//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./org/minima/objects/base/MiniHash.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMinimaObjectsBaseMiniHash")
#ifdef RESTRICT_OrgMinimaObjectsBaseMiniHash
#define INCLUDE_ALL_OrgMinimaObjectsBaseMiniHash 0
#else
#define INCLUDE_ALL_OrgMinimaObjectsBaseMiniHash 1
#endif
#undef RESTRICT_OrgMinimaObjectsBaseMiniHash

#if !defined (OrgMinimaObjectsBaseMiniHash_) && (INCLUDE_ALL_OrgMinimaObjectsBaseMiniHash || defined(INCLUDE_OrgMinimaObjectsBaseMiniHash))
#define OrgMinimaObjectsBaseMiniHash_

#define RESTRICT_OrgMinimaObjectsBaseMiniData 1
#define INCLUDE_OrgMinimaObjectsBaseMiniData 1
#include "org/minima/objects/base/MiniData.h"

@class IOSByteArray;
@class IOSObjectArray;
@class JavaIoDataInputStream;
@class JavaIoDataOutputStream;

@interface OrgMinimaObjectsBaseMiniHash : OrgMinimaObjectsBaseMiniData

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithByteArray:(IOSByteArray *)zData;

- (instancetype)initWithNSString:(NSString *)zHex;

+ (NSString *)ensureSizeWithNSString:(NSString *)zHEX;

+ (OrgMinimaObjectsBaseMiniHash *)getRandomData;

+ (void)mainWithNSStringArray:(IOSObjectArray *)zArgs;

- (void)readDataStreamWithJavaIoDataInputStream:(JavaIoDataInputStream *)zIn;

+ (OrgMinimaObjectsBaseMiniHash *)ReadFromStreamWithJavaIoDataInputStream:(JavaIoDataInputStream *)zIn;

- (void)writeDataStreamWithJavaIoDataOutputStream:(JavaIoDataOutputStream *)zOut;

@end

J2OBJC_STATIC_INIT(OrgMinimaObjectsBaseMiniHash)

inline jint OrgMinimaObjectsBaseMiniHash_get_HASH_LENGTH(void);
#define OrgMinimaObjectsBaseMiniHash_HASH_LENGTH 32
J2OBJC_STATIC_FIELD_CONSTANT(OrgMinimaObjectsBaseMiniHash, HASH_LENGTH, jint)

inline OrgMinimaObjectsBaseMiniHash *OrgMinimaObjectsBaseMiniHash_get_ZERO32(void);
inline OrgMinimaObjectsBaseMiniHash *OrgMinimaObjectsBaseMiniHash_set_ZERO32(OrgMinimaObjectsBaseMiniHash *value);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT OrgMinimaObjectsBaseMiniHash *OrgMinimaObjectsBaseMiniHash_ZERO32;
J2OBJC_STATIC_FIELD_OBJ(OrgMinimaObjectsBaseMiniHash, ZERO32, OrgMinimaObjectsBaseMiniHash *)

FOUNDATION_EXPORT void OrgMinimaObjectsBaseMiniHash_init(OrgMinimaObjectsBaseMiniHash *self);

FOUNDATION_EXPORT OrgMinimaObjectsBaseMiniHash *new_OrgMinimaObjectsBaseMiniHash_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaObjectsBaseMiniHash *create_OrgMinimaObjectsBaseMiniHash_init(void);

FOUNDATION_EXPORT void OrgMinimaObjectsBaseMiniHash_initWithByteArray_(OrgMinimaObjectsBaseMiniHash *self, IOSByteArray *zData);

FOUNDATION_EXPORT OrgMinimaObjectsBaseMiniHash *new_OrgMinimaObjectsBaseMiniHash_initWithByteArray_(IOSByteArray *zData) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaObjectsBaseMiniHash *create_OrgMinimaObjectsBaseMiniHash_initWithByteArray_(IOSByteArray *zData);

FOUNDATION_EXPORT void OrgMinimaObjectsBaseMiniHash_initWithNSString_(OrgMinimaObjectsBaseMiniHash *self, NSString *zHex);

FOUNDATION_EXPORT OrgMinimaObjectsBaseMiniHash *new_OrgMinimaObjectsBaseMiniHash_initWithNSString_(NSString *zHex) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMinimaObjectsBaseMiniHash *create_OrgMinimaObjectsBaseMiniHash_initWithNSString_(NSString *zHex);

FOUNDATION_EXPORT NSString *OrgMinimaObjectsBaseMiniHash_ensureSizeWithNSString_(NSString *zHEX);

FOUNDATION_EXPORT OrgMinimaObjectsBaseMiniHash *OrgMinimaObjectsBaseMiniHash_getRandomData(void);

FOUNDATION_EXPORT OrgMinimaObjectsBaseMiniHash *OrgMinimaObjectsBaseMiniHash_ReadFromStreamWithJavaIoDataInputStream_(JavaIoDataInputStream *zIn);

FOUNDATION_EXPORT void OrgMinimaObjectsBaseMiniHash_mainWithNSStringArray_(IOSObjectArray *zArgs);

J2OBJC_TYPE_LITERAL_HEADER(OrgMinimaObjectsBaseMiniHash)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMinimaObjectsBaseMiniHash")
